/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as EducatorRouteRouteImport } from './routes/educator/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EducatorIndexRouteImport } from './routes/educator/index'
import { Route as EducatorDashboardRouteImport } from './routes/educator/dashboard'
import { Route as EducatorClassesRouteImport } from './routes/educator/classes'
import { Route as EducatorAssignRouteImport } from './routes/educator/assign'
import { Route as EducatorAssessmentRouteImport } from './routes/educator/assessment'
import { Route as EducatorAnalyticsRouteImport } from './routes/educator/analytics'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedModesRouteImport } from './routes/_authenticated/modes'
import { Route as AuthenticatedDrugsRouteImport } from './routes/_authenticated/drugs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedGameWarehousingRouteImport } from './routes/_authenticated/game.warehousing'
import { Route as AuthenticatedGameIndustryRouteImport } from './routes/_authenticated/game.industry'
import { Route as AuthenticatedGameHospitalRouteImport } from './routes/_authenticated/game.hospital'
import { Route as AuthenticatedGameCommunityRouteImport } from './routes/_authenticated/game.community'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EducatorRouteRoute = EducatorRouteRouteImport.update({
  id: '/educator',
  path: '/educator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EducatorIndexRoute = EducatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EducatorRouteRoute,
} as any)
const EducatorDashboardRoute = EducatorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EducatorRouteRoute,
} as any)
const EducatorClassesRoute = EducatorClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => EducatorRouteRoute,
} as any)
const EducatorAssignRoute = EducatorAssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => EducatorRouteRoute,
} as any)
const EducatorAssessmentRoute = EducatorAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => EducatorRouteRoute,
} as any)
const EducatorAnalyticsRoute = EducatorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => EducatorRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModesRoute = AuthenticatedModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDrugsRoute = AuthenticatedDrugsRouteImport.update({
  id: '/drugs',
  path: '/drugs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGameWarehousingRoute =
  AuthenticatedGameWarehousingRouteImport.update({
    id: '/game/warehousing',
    path: '/game/warehousing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGameIndustryRoute =
  AuthenticatedGameIndustryRouteImport.update({
    id: '/game/industry',
    path: '/game/industry',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGameHospitalRoute =
  AuthenticatedGameHospitalRouteImport.update({
    id: '/game/hospital',
    path: '/game/hospital',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGameCommunityRoute =
  AuthenticatedGameCommunityRouteImport.update({
    id: '/game/community',
    path: '/game/community',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/educator': typeof EducatorRouteRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drugs': typeof AuthenticatedDrugsRoute
  '/modes': typeof AuthenticatedModesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/educator/analytics': typeof EducatorAnalyticsRoute
  '/educator/assessment': typeof EducatorAssessmentRoute
  '/educator/assign': typeof EducatorAssignRoute
  '/educator/classes': typeof EducatorClassesRoute
  '/educator/dashboard': typeof EducatorDashboardRoute
  '/educator/': typeof EducatorIndexRoute
  '/game/community': typeof AuthenticatedGameCommunityRoute
  '/game/hospital': typeof AuthenticatedGameHospitalRoute
  '/game/industry': typeof AuthenticatedGameIndustryRoute
  '/game/warehousing': typeof AuthenticatedGameWarehousingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drugs': typeof AuthenticatedDrugsRoute
  '/modes': typeof AuthenticatedModesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/educator/analytics': typeof EducatorAnalyticsRoute
  '/educator/assessment': typeof EducatorAssessmentRoute
  '/educator/assign': typeof EducatorAssignRoute
  '/educator/classes': typeof EducatorClassesRoute
  '/educator/dashboard': typeof EducatorDashboardRoute
  '/educator': typeof EducatorIndexRoute
  '/game/community': typeof AuthenticatedGameCommunityRoute
  '/game/hospital': typeof AuthenticatedGameHospitalRoute
  '/game/industry': typeof AuthenticatedGameIndustryRoute
  '/game/warehousing': typeof AuthenticatedGameWarehousingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/educator': typeof EducatorRouteRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drugs': typeof AuthenticatedDrugsRoute
  '/_authenticated/modes': typeof AuthenticatedModesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/educator/analytics': typeof EducatorAnalyticsRoute
  '/educator/assessment': typeof EducatorAssessmentRoute
  '/educator/assign': typeof EducatorAssignRoute
  '/educator/classes': typeof EducatorClassesRoute
  '/educator/dashboard': typeof EducatorDashboardRoute
  '/educator/': typeof EducatorIndexRoute
  '/_authenticated/game/community': typeof AuthenticatedGameCommunityRoute
  '/_authenticated/game/hospital': typeof AuthenticatedGameHospitalRoute
  '/_authenticated/game/industry': typeof AuthenticatedGameIndustryRoute
  '/_authenticated/game/warehousing': typeof AuthenticatedGameWarehousingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/educator'
    | '/leaderboard'
    | '/login'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/drugs'
    | '/modes'
    | '/profile'
    | '/settings'
    | '/auth/callback'
    | '/educator/analytics'
    | '/educator/assessment'
    | '/educator/assign'
    | '/educator/classes'
    | '/educator/dashboard'
    | '/educator/'
    | '/game/community'
    | '/game/hospital'
    | '/game/industry'
    | '/game/warehousing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/login'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/drugs'
    | '/modes'
    | '/profile'
    | '/settings'
    | '/auth/callback'
    | '/educator/analytics'
    | '/educator/assessment'
    | '/educator/assign'
    | '/educator/classes'
    | '/educator/dashboard'
    | '/educator'
    | '/game/community'
    | '/game/hospital'
    | '/game/industry'
    | '/game/warehousing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/educator'
    | '/leaderboard'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/drugs'
    | '/_authenticated/modes'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/educator/analytics'
    | '/educator/assessment'
    | '/educator/assign'
    | '/educator/classes'
    | '/educator/dashboard'
    | '/educator/'
    | '/_authenticated/game/community'
    | '/_authenticated/game/hospital'
    | '/_authenticated/game/industry'
    | '/_authenticated/game/warehousing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EducatorRouteRoute: typeof EducatorRouteRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educator': {
      id: '/educator'
      path: '/educator'
      fullPath: '/educator'
      preLoaderRoute: typeof EducatorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educator/': {
      id: '/educator/'
      path: '/'
      fullPath: '/educator/'
      preLoaderRoute: typeof EducatorIndexRouteImport
      parentRoute: typeof EducatorRouteRoute
    }
    '/educator/dashboard': {
      id: '/educator/dashboard'
      path: '/dashboard'
      fullPath: '/educator/dashboard'
      preLoaderRoute: typeof EducatorDashboardRouteImport
      parentRoute: typeof EducatorRouteRoute
    }
    '/educator/classes': {
      id: '/educator/classes'
      path: '/classes'
      fullPath: '/educator/classes'
      preLoaderRoute: typeof EducatorClassesRouteImport
      parentRoute: typeof EducatorRouteRoute
    }
    '/educator/assign': {
      id: '/educator/assign'
      path: '/assign'
      fullPath: '/educator/assign'
      preLoaderRoute: typeof EducatorAssignRouteImport
      parentRoute: typeof EducatorRouteRoute
    }
    '/educator/assessment': {
      id: '/educator/assessment'
      path: '/assessment'
      fullPath: '/educator/assessment'
      preLoaderRoute: typeof EducatorAssessmentRouteImport
      parentRoute: typeof EducatorRouteRoute
    }
    '/educator/analytics': {
      id: '/educator/analytics'
      path: '/analytics'
      fullPath: '/educator/analytics'
      preLoaderRoute: typeof EducatorAnalyticsRouteImport
      parentRoute: typeof EducatorRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modes': {
      id: '/_authenticated/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof AuthenticatedModesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drugs': {
      id: '/_authenticated/drugs'
      path: '/drugs'
      fullPath: '/drugs'
      preLoaderRoute: typeof AuthenticatedDrugsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game/warehousing': {
      id: '/_authenticated/game/warehousing'
      path: '/game/warehousing'
      fullPath: '/game/warehousing'
      preLoaderRoute: typeof AuthenticatedGameWarehousingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game/industry': {
      id: '/_authenticated/game/industry'
      path: '/game/industry'
      fullPath: '/game/industry'
      preLoaderRoute: typeof AuthenticatedGameIndustryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game/hospital': {
      id: '/_authenticated/game/hospital'
      path: '/game/hospital'
      fullPath: '/game/hospital'
      preLoaderRoute: typeof AuthenticatedGameHospitalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game/community': {
      id: '/_authenticated/game/community'
      path: '/game/community'
      fullPath: '/game/community'
      preLoaderRoute: typeof AuthenticatedGameCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDrugsRoute: typeof AuthenticatedDrugsRoute
  AuthenticatedModesRoute: typeof AuthenticatedModesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedGameCommunityRoute: typeof AuthenticatedGameCommunityRoute
  AuthenticatedGameHospitalRoute: typeof AuthenticatedGameHospitalRoute
  AuthenticatedGameIndustryRoute: typeof AuthenticatedGameIndustryRoute
  AuthenticatedGameWarehousingRoute: typeof AuthenticatedGameWarehousingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDrugsRoute: AuthenticatedDrugsRoute,
  AuthenticatedModesRoute: AuthenticatedModesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedGameCommunityRoute: AuthenticatedGameCommunityRoute,
  AuthenticatedGameHospitalRoute: AuthenticatedGameHospitalRoute,
  AuthenticatedGameIndustryRoute: AuthenticatedGameIndustryRoute,
  AuthenticatedGameWarehousingRoute: AuthenticatedGameWarehousingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EducatorRouteRouteChildren {
  EducatorAnalyticsRoute: typeof EducatorAnalyticsRoute
  EducatorAssessmentRoute: typeof EducatorAssessmentRoute
  EducatorAssignRoute: typeof EducatorAssignRoute
  EducatorClassesRoute: typeof EducatorClassesRoute
  EducatorDashboardRoute: typeof EducatorDashboardRoute
  EducatorIndexRoute: typeof EducatorIndexRoute
}

const EducatorRouteRouteChildren: EducatorRouteRouteChildren = {
  EducatorAnalyticsRoute: EducatorAnalyticsRoute,
  EducatorAssessmentRoute: EducatorAssessmentRoute,
  EducatorAssignRoute: EducatorAssignRoute,
  EducatorClassesRoute: EducatorClassesRoute,
  EducatorDashboardRoute: EducatorDashboardRoute,
  EducatorIndexRoute: EducatorIndexRoute,
}

const EducatorRouteRouteWithChildren = EducatorRouteRoute._addFileChildren(
  EducatorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EducatorRouteRoute: EducatorRouteRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
