/**
 * Brand names in this catalogue close enough to be mistaken for each other.
 *
 * GENERATED. Produced by `findConfusablePairs` in ./lookalike.ts over all
 * 1286 Pakistani brand names in the `drug_brands` table, on 2026-09-13.
 * The ordering is canonical, so regenerating against the same catalogue gives
 * a byte-identical file and a review of it stays valid.
 *
 * THESE ARE CANDIDATES, NOT FINDINGS. The measurement is orthographic: how
 * close two names are to read, to type, or to hear across a counter. It is not
 * evidence that any pair has ever been confused in a Pakistani pharmacy, which
 * would need incident data and a pharmacist. Several of these do appear on the
 * international confused-drug-name lists, which is a reason to take the method
 * seriously and not a reason to treat the rest as verified.
 *
 * Nothing that uses this file depends on that judgement. The task built from a
 * pair is "the prescription says this one, hand over this one" - reading
 * accuracy, asserting no pharmacology at all.
 *
 * To regenerate: read `drug_brands` joined to `drugs`, map each row to a
 * BrandRow ({ brand, drugId, generic, drugClass }), pass the lot to
 * findConfusablePairs, and print the result in this shape. The ordering and
 * the deduplication are handled there, so the output is stable.
 */

export type LookalikePair = {
  a: string; aGeneric: string; aClass: string;
  b: string; bGeneric: string; bClass: string;
  distance: number;
  /** The two medicines are in different therapeutic classes. */
  crossClass: boolean;
};

/** How many brand names the scan covered, for the figure the drill quotes. */
export const BRANDS_SCANNED = 1286;

export const LOOKALIKE_PAIRS: LookalikePair[] = [
  { a: "Zoltan", aGeneric: "Pantoprazole", aClass: "PPI",
    b: "Zoltar", bGeneric: "Esomeprazole", bClass: "Proton pump inhibitors",
    distance: 1, crossClass: true },
  { a: "Clopid", aGeneric: "Clopidogrel", aClass: "P2Y12 Platelet Inhibitor",
    b: "Lopid", bGeneric: "Gemfibrozil", bClass: "Fibrates",
    distance: 1, crossClass: true },
  { a: "Claritek", aGeneric: "Clarithromycin", aClass: "Macrolide",
    b: "Claritin", bGeneric: "Loratadine", bClass: "2nd-gen Antihistamine",
    distance: 2, crossClass: true },
  { a: "Clarinex", aGeneric: "Desloratadine", aClass: "Second-generation Antihistamine",
    b: "Claritek", bGeneric: "Clarithromycin", bClass: "Macrolide",
    distance: 2, crossClass: true },
  { a: "Cytomel", aGeneric: "Liothyronine", aClass: "Thyroid hormones",
    b: "Cytotec", bGeneric: "Misoprostol", bClass: "Propionic acid derivatives",
    distance: 2, crossClass: true },
  { a: "Avonex", aGeneric: "Interferon Beta-1A", aClass: "Interferons",
    b: "Avopef", bGeneric: "Etoposide", bClass: "Topoisomerase Inhibitor",
    distance: 2, crossClass: true },
  { a: "Cefotan", aGeneric: "Cefotetan", aClass: "Second-generation cephalosporins",
    b: "Cefspan", bGeneric: "Cefixime", bClass: "3rd-gen Cephalosporin",
    distance: 2, crossClass: true },
  { a: "Ecolab", aGeneric: "Triclosan", aClass: "Medicated dressings with antiinfectives",
    b: "Ecoza", bGeneric: "Econazole", bClass: "Imidazole derivatives",
    distance: 2, crossClass: true },
  { a: "Lopid", aGeneric: "Gemfibrozil", aClass: "Fibrates",
    b: "Loprin", bGeneric: "Acetylsalicylic Acid", bClass: "NSAID/Antiplatelet",
    distance: 2, crossClass: true },
  { a: "Provas", aGeneric: "Acetaminophen", aClass: "Analgesic/Antipyretic",
    b: "Prozac", bGeneric: "Fluoxetine", bClass: "SSRI",
    distance: 2, crossClass: true },
  { a: "Zetia", aGeneric: "Ezetimibe", aClass: "Other lipid modifying agents",
    b: "Zetro", bGeneric: "Azithromycin", bClass: "Macrolide Antibiotic",
    distance: 2, crossClass: true },
  { a: "Aceon", aGeneric: "Perindopril", aClass: "ACE Inhibitor",
    b: "Actos", bGeneric: "Pioglitazone", bClass: "Thiazolidinedione",
    distance: 2, crossClass: true },
  { a: "Bm Calc Sulph", aGeneric: "Calcarea Sulphurica", aClass: "Blood Coagulation Factor",
    b: "Bm Kali Sulph", bGeneric: "Kali Sulphuricum", bClass: "Osmotic Laxative",
    distance: 2, crossClass: true },
  { a: "Demerol", aGeneric: "Meperidine", aClass: "Phenylpiperidine derivatives",
    b: "Detrol", bGeneric: "Tolterodine", bClass: "Cholinergic Muscarinic Antagonist",
    distance: 2, crossClass: true },
  { a: "Domel", aGeneric: "Domperidone", aClass: "Dopamine Antagonist",
    b: "Doxil", bGeneric: "Doxorubicin", bClass: "Anthracycline",
    distance: 2, crossClass: true },
  { a: "Glumet", aGeneric: "Metformin", aClass: "Biguanide",
    b: "Glyset", bGeneric: "Miglitol", bClass: "Alpha-glucosidase Inhibitor",
    distance: 2, crossClass: true },
  { a: "Medrol", aGeneric: "Methylprednisolone", aClass: "Corticosteroids, potent (group III)",
    b: "Mepron", bGeneric: "Atovaquone", bClass: "Biguanides",
    distance: 2, crossClass: true },
  { a: "Zofran", aGeneric: "Ondansetron", aClass: "5-HT3 Antagonist",
    b: "Zoltan", bGeneric: "Pantoprazole", bClass: "PPI",
    distance: 2, crossClass: true },
  { a: "Alrex", aGeneric: "Loteprednol Etabonate", aClass: "Corticosteroid",
    b: "Amrix", bGeneric: "Cyclobenzaprine", bClass: "Other centrally acting agents",
    distance: 2, crossClass: true },
  { a: "Arestin", aGeneric: "Minocycline", aClass: "Tetracycline",
    b: "Avastin", bGeneric: "Bevacizumab", bClass: "VEGF/VEGFR (Vascular Endothelial Growth Factor / -Receptor) inhibitors",
    distance: 2, crossClass: true },
  { a: "Neoral", aGeneric: "Cyclosporine", aClass: "Calcineurin Inhibitor",
    b: "Nizoral", bGeneric: "Ketoconazole", bClass: "Imidazole derivatives",
    distance: 2, crossClass: true },
  { a: "Zioptan", aGeneric: "Tafluprost", aClass: "Prostaglandin analogues",
    b: "Zoltan", bGeneric: "Pantoprazole", bClass: "PPI",
    distance: 2, crossClass: true },
  { a: "Alcaine", aGeneric: "Proparacaine", aClass: "Local anesthetics",
    b: "Marcaine", bGeneric: "Bupivacaine", bClass: "Amides",
    distance: 2, crossClass: true },
  { a: "Alrex", aGeneric: "Loteprednol Etabonate", aClass: "Corticosteroid",
    b: "Flarex", bGeneric: "Fluorometholone", bClass: "Corticosteroids",
    distance: 2, crossClass: true },
  { a: "Altace", aGeneric: "Ramipril", aClass: "ACE Inhibitor",
    b: "Ultane", bGeneric: "Sevoflurane", bClass: "Halogenated hydrocarbons",
    distance: 2, crossClass: true },
  { a: "Amoxil", aGeneric: "Amoxicillin", aClass: "Penicillin Antibiotic",
    b: "Doxil", bGeneric: "Doxorubicin", bClass: "Anthracycline",
    distance: 2, crossClass: true },
  { a: "Arava", aGeneric: "Leflunomide", aClass: "DMARD",
    b: "Xerava", bGeneric: "Eravacycline", bClass: "Tetracyclines",
    distance: 2, crossClass: true },
  { a: "Borax", aGeneric: "Sodium Borate", aClass: "Antiinfectives",
    b: "Doryx", bGeneric: "Doxycycline", bClass: "Tetracycline",
    distance: 2, crossClass: true },
  { a: "Borax", aGeneric: "Sodium Borate", aClass: "Antiinfectives",
    b: "Movax", bGeneric: "Tizanidine", bClass: "Other centrally acting agents",
    distance: 2, crossClass: true },
  { a: "Calan", aGeneric: "Verapamil", aClass: "Calcium Channel Blocker",
    b: "Dulan", bGeneric: "Duloxetine", bClass: "SNRI",
    distance: 2, crossClass: true },
  { a: "Concor", aGeneric: "Bisoprolol", aClass: "Beta-blocker",
    b: "Zocor", bGeneric: "Simvastatin", bClass: "Dipeptidyl peptidase 4 (DPP-4) inhibitors",
    distance: 2, crossClass: true },
  { a: "Demerol", aGeneric: "Meperidine", aClass: "Phenylpiperidine derivatives",
    b: "Remeron", bGeneric: "Mirtazapine", bClass: "Other antidepressants",
    distance: 2, crossClass: true },
  { a: "Detrol", aGeneric: "Tolterodine", aClass: "Cholinergic Muscarinic Antagonist",
    b: "Getryl", bGeneric: "Glimepiride", bClass: "Sulfonylurea",
    distance: 2, crossClass: true },
  { a: "Detrol", aGeneric: "Tolterodine", aClass: "Cholinergic Muscarinic Antagonist",
    b: "Medrol", bGeneric: "Methylprednisolone", bClass: "Corticosteroids, potent (group III)",
    distance: 2, crossClass: true },
  { a: "Doxil", aGeneric: "Doxorubicin", aClass: "Anthracycline",
    b: "Paxil", bGeneric: "Paroxetine", bClass: "SSRI",
    distance: 2, crossClass: true },
  { a: "Dulan", aGeneric: "Duloxetine", aClass: "SNRI",
    b: "Sular", bGeneric: "Nisoldipine", bClass: "Calcium Channel Blocker",
    distance: 2, crossClass: true },
  { a: "Emend", aGeneric: "Aprepitant", aClass: "Other antiemetics",
    b: "Vfend", bGeneric: "Voriconazole", bClass: "Azole Antifungal",
    distance: 2, crossClass: true },
  { a: "Forane", aGeneric: "Isoflurane", aClass: "Halogenated hydrocarbons",
    b: "Lorano", bGeneric: "Loratadine", bClass: "2nd-gen Antihistamine",
    distance: 2, crossClass: true },
  { a: "Fosamax", aGeneric: "Alendronate", aClass: "Bisphosphonate",
    b: "Topamax", bGeneric: "Topiramate", bClass: "Centrally acting antiobesity products",
    distance: 2, crossClass: true },
  { a: "Indocin", aGeneric: "Indomethacin", aClass: "Antiinflammatory agents, non-steroids",
    b: "Lincocin", bGeneric: "Lincomycin", bClass: "Lincosamides",
    distance: 2, crossClass: true },
  { a: "Indocin", aGeneric: "Indomethacin", aClass: "Antiinflammatory agents, non-steroids",
    b: "Minocin", bGeneric: "Minocycline", bClass: "Tetracycline",
    distance: 2, crossClass: true },
  { a: "Isoptin", aGeneric: "Verapamil", aClass: "Calcium Channel Blocker",
    b: "Softin", bGeneric: "Loratadine", bClass: "2nd-gen Antihistamine",
    distance: 2, crossClass: true },
  { a: "Kybella", aGeneric: "Deoxycholic Acid", aClass: "Other dermatologicals",
    b: "V-Bella", bGeneric: "Boric Acid", bClass: "Antiinfectives",
    distance: 2, crossClass: true },
  { a: "Lincocin", aGeneric: "Lincomycin", aClass: "Lincosamides",
    b: "Minocin", bGeneric: "Minocycline", bClass: "Tetracycline",
    distance: 2, crossClass: true },
  { a: "Lincocin", aGeneric: "Lincomycin", aClass: "Lincosamides",
    b: "Vancocin", bGeneric: "Vancomycin", bClass: "Antibiotics",
    distance: 2, crossClass: true },
  { a: "Naftin", aGeneric: "Naftifine", aClass: "Other antifungals for topical use",
    b: "Softin", bGeneric: "Loratadine", bClass: "2nd-gen Antihistamine",
    distance: 2, crossClass: true },
  { a: "Nasal", aGeneric: "Oxymetazoline", aClass: "Sympathomimetics used as decongestants",
    b: "Qnasl", bGeneric: "Beclomethasone", bClass: "Corticosteroids, potent (group III)",
    distance: 2, crossClass: true },
  { a: "Neoral", aGeneric: "Cyclosporine", aClass: "Calcineurin Inhibitor",
    b: "Tegral", bGeneric: "Carbamazepine", bClass: "Carboxamide derivatives",
    distance: 2, crossClass: true },
  { a: "Neupro", aGeneric: "Rotigotine", aClass: "Dopamine agonists",
    b: "ReoPro", bGeneric: "Abciximab", bClass: "Glycoprotein IIb/IIIa Inhibitor",
    distance: 2, crossClass: true },
  { a: "Polocaine", aGeneric: "Mepivacaine", aClass: "Amides",
    b: "Xylocaine", bGeneric: "Lidocaine HCl", bClass: "Local Anesthetic / Antiarrhythmic",
    distance: 2, crossClass: true },
  { a: "Restoril", aGeneric: "Temazepam", aClass: "Benzodiazepine derivatives",
    b: "Zestril", bGeneric: "Lisinopril", bClass: "ACE Inhibitor",
    distance: 2, crossClass: true },
  { a: "Tigan", aGeneric: "Trimethobenzamide", aClass: "Aminoalkyl ethers",
    b: "Zirgan", bGeneric: "Ganciclovir", bClass: "Antivirals",
    distance: 2, crossClass: true },
  { a: "Lotrimin", aGeneric: "Clotrimazole", aClass: "Imidazole derivatives",
    b: "Lotrimin AF", bGeneric: "Clotrimazole 1%", bClass: "Topical Antifungal",
    distance: 3, crossClass: true },
  { a: "Advil", aGeneric: "Ibuprofen", aClass: "NSAID",
    b: "Auvi-Q", bGeneric: "Adrenaline", bClass: "Sympathomimetic",
    distance: 3, crossClass: true },
  { a: "Polocaine-Mpf", aGeneric: "Mepivacaine", aClass: "Amides",
    b: "Xylocaine Mpf", bGeneric: "Lidocaine HCl", bClass: "Local Anesthetic / Antiarrhythmic",
    distance: 3, crossClass: true },
];
