-- Indications, side effects and contraindications for the 77 book-derived drugs.
--
-- 20260828170000 loaded these with name, class and brand only, so they reached
-- the Study list as cards reading "Indications: —" and could never produce a
-- quiz question beyond drug class. That was the right call for *doses*, which
-- extraction mangled, but wrong to extend to the rest of the clinical picture:
-- a drug class and its main indications are stable, unambiguous facts.
--
-- These are written deliberately rather than extracted, for the same reason the
-- classes were: the source PDF's column merging cannot be trusted per-field.
-- Each entry is the standard teaching answer - the indications a pharmacist
-- would expect, the side effects that actually get counselled on, and the
-- contraindications that should stop a supply.
--
-- `dosage` is still deliberately left empty and `needs_review` stays true. A
-- wrong dose remains the most harmful thing this product could contain, and
-- nothing here changes the fact that no pharmacist has signed these off yet.
-- The UI now shows that state rather than hiding it.

UPDATE public.drugs d
SET indications       = v.indications,
    side_effects      = v.side_effects,
    contraindications = v.contraindications
FROM (VALUES
  ('Abatacept',
   ARRAY['Rheumatoid arthritis','Juvenile idiopathic arthritis'],
   ARRAY['Headache','Upper respiratory infection','Infusion reaction'],
   ARRAY['Serious active infection']),
  ('Abciximab',
   ARRAY['Percutaneous coronary intervention','Acute coronary syndrome'],
   ARRAY['Bleeding','Thrombocytopenia','Hypotension'],
   ARRAY['Active internal bleeding','Recent stroke','Severe uncontrolled hypertension']),
  ('Acarbose',
   ARRAY['Type 2 diabetes'],
   ARRAY['Flatulence','Diarrhoea','Abdominal discomfort'],
   ARRAY['Inflammatory bowel disease','Intestinal obstruction','Severe renal impairment']),
  ('Acebutolol',
   ARRAY['Hypertension','Ventricular arrhythmias'],
   ARRAY['Fatigue','Bradycardia','Cold extremities'],
   ARRAY['Asthma','Severe bradycardia','Second or third degree heart block']),
  ('Adalimumab',
   ARRAY['Rheumatoid arthritis','Crohn disease','Plaque psoriasis'],
   ARRAY['Injection site reaction','Infection','Headache'],
   ARRAY['Serious active infection','Untreated tuberculosis']),
  ('Alendronate',
   ARRAY['Osteoporosis','Paget disease of bone'],
   ARRAY['Oesophageal irritation','Abdominal pain','Musculoskeletal pain'],
   ARRAY['Oesophageal stricture','Inability to sit upright for 30 minutes','Hypocalcaemia']),
  ('Amiloride',
   ARRAY['Oedema','Hypertension'],
   ARRAY['Hyperkalaemia','Nausea','Headache'],
   ARRAY['Hyperkalaemia','Severe renal impairment','Anuria']),
  ('Anakinra',
   ARRAY['Rheumatoid arthritis'],
   ARRAY['Injection site reaction','Neutropenia','Infection'],
   ARRAY['Serious active infection','Neutropenia']),
  ('Azathioprine',
   ARRAY['Prophylaxis of transplant rejection','Autoimmune disease'],
   ARRAY['Bone marrow suppression','Nausea','Hepatotoxicity'],
   ARRAY['Pregnancy','Serious active infection']),
  ('Basiliximab',
   ARRAY['Prophylaxis of renal transplant rejection'],
   ARRAY['Infection','Hypersensitivity reaction','Gastrointestinal upset'],
   ARRAY['Hypersensitivity to basiliximab']),
  ('Benazepril',
   ARRAY['Hypertension'],
   ARRAY['Dry cough','Hyperkalaemia','Dizziness'],
   ARRAY['Pregnancy','Angioedema with a previous ACE inhibitor','Bilateral renal artery stenosis']),
  ('Betaxolol',
   ARRAY['Hypertension','Open-angle glaucoma'],
   ARRAY['Fatigue','Bradycardia','Dizziness'],
   ARRAY['Asthma','Severe bradycardia','Second or third degree heart block']),
  ('Bisoprolol',
   ARRAY['Hypertension','Chronic heart failure'],
   ARRAY['Fatigue','Bradycardia','Dizziness'],
   ARRAY['Asthma','Severe bradycardia','Acute decompensated heart failure']),
  ('Bromocriptine',
   ARRAY['Hyperprolactinaemia','Parkinson disease','Type 2 diabetes'],
   ARRAY['Nausea','Postural hypotension','Headache'],
   ARRAY['Uncontrolled hypertension','Ischaemic heart disease']),
  ('Candesartan',
   ARRAY['Hypertension','Chronic heart failure'],
   ARRAY['Dizziness','Hyperkalaemia','Hypotension'],
   ARRAY['Pregnancy','Bilateral renal artery stenosis']),
  ('Captopril',
   ARRAY['Hypertension','Heart failure','Diabetic nephropathy'],
   ARRAY['Dry cough','Taste disturbance','Hyperkalaemia'],
   ARRAY['Pregnancy','Angioedema with a previous ACE inhibitor','Bilateral renal artery stenosis']),
  ('Carvedilol',
   ARRAY['Chronic heart failure','Hypertension'],
   ARRAY['Dizziness','Fatigue','Bradycardia'],
   ARRAY['Asthma','Severe bradycardia','Acute decompensated heart failure']),
  ('Celecoxib',
   ARRAY['Osteoarthritis','Rheumatoid arthritis','Acute pain'],
   ARRAY['Dyspepsia','Oedema','Raised blood pressure'],
   ARRAY['Sulfonamide hypersensitivity','Active peptic ulcer','Severe heart failure']),
  ('Certolizumab',
   ARRAY['Crohn disease','Rheumatoid arthritis'],
   ARRAY['Infection','Injection site reaction','Rash'],
   ARRAY['Serious active infection','Untreated tuberculosis']),
  ('Chlorothiazide',
   ARRAY['Hypertension','Oedema'],
   ARRAY['Hypokalaemia','Hyponatraemia','Hyperuricaemia'],
   ARRAY['Anuria','Sulfonamide hypersensitivity']),
  ('Citalopram',
   ARRAY['Major depression'],
   ARRAY['Nausea','Insomnia','Sexual dysfunction','QT prolongation'],
   ARRAY['Concurrent MAO inhibitor','Congenital long QT syndrome']),
  ('Clomipramine',
   ARRAY['Obsessive-compulsive disorder','Major depression'],
   ARRAY['Dry mouth','Sedation','Constipation','Postural hypotension'],
   ARRAY['Recent myocardial infarction','Concurrent MAO inhibitor']),
  ('Clonidine',
   ARRAY['Hypertension','Attention deficit hyperactivity disorder','Menopausal flushing'],
   ARRAY['Sedation','Dry mouth','Rebound hypertension on abrupt withdrawal'],
   ARRAY['Severe bradyarrhythmia']),
  ('Colesevelam',
   ARRAY['Hypercholesterolaemia','Type 2 diabetes'],
   ARRAY['Constipation','Dyspepsia','Flatulence'],
   ARRAY['Bowel obstruction','Serum triglycerides above 500 mg/dL']),
  ('Cyclosporine',
   ARRAY['Prophylaxis of transplant rejection','Severe psoriasis','Rheumatoid arthritis'],
   ARRAY['Nephrotoxicity','Hypertension','Gingival hyperplasia','Tremor'],
   ARRAY['Uncontrolled hypertension','Severe renal impairment','Serious active infection']),
  ('Diltiazem',
   ARRAY['Hypertension','Angina','Supraventricular tachycardia'],
   ARRAY['Ankle oedema','Bradycardia','Constipation'],
   ARRAY['Severe bradycardia','Second or third degree heart block','Systolic heart failure']),
  ('Duloxetine',
   ARRAY['Major depression','Generalised anxiety disorder','Diabetic neuropathic pain'],
   ARRAY['Nausea','Dry mouth','Insomnia'],
   ARRAY['Concurrent MAO inhibitor','Uncontrolled narrow-angle glaucoma']),
  ('Enalapril',
   ARRAY['Hypertension','Heart failure'],
   ARRAY['Dry cough','Hyperkalaemia','Dizziness'],
   ARRAY['Pregnancy','Angioedema with a previous ACE inhibitor','Bilateral renal artery stenosis']),
  ('Eplerenone',
   ARRAY['Heart failure after myocardial infarction','Hypertension'],
   ARRAY['Hyperkalaemia','Dizziness','Raised serum creatinine'],
   ARRAY['Hyperkalaemia','Severe renal impairment']),
  ('Etanercept',
   ARRAY['Rheumatoid arthritis','Plaque psoriasis','Ankylosing spondylitis'],
   ARRAY['Injection site reaction','Infection','Headache'],
   ARRAY['Serious active infection','Sepsis']),
  ('Everolimus',
   ARRAY['Prophylaxis of transplant rejection','Renal cell carcinoma'],
   ARRAY['Stomatitis','Hyperlipidaemia','Impaired wound healing'],
   ARRAY['Hypersensitivity to sirolimus derivatives']),
  ('Exenatide',
   ARRAY['Type 2 diabetes'],
   ARRAY['Nausea','Vomiting','Injection site reaction','Pancreatitis'],
   ARRAY['Severe renal impairment','History of pancreatitis']),
  ('Felodipine',
   ARRAY['Hypertension','Angina'],
   ARRAY['Ankle oedema','Flushing','Headache'],
   ARRAY['Cardiogenic shock','Unstable angina','Severe aortic stenosis']),
  ('Fosinopril',
   ARRAY['Hypertension','Heart failure'],
   ARRAY['Dry cough','Dizziness','Hyperkalaemia'],
   ARRAY['Pregnancy','Angioedema with a previous ACE inhibitor','Bilateral renal artery stenosis']),
  ('Gabapentin',
   ARRAY['Neuropathic pain','Partial seizures'],
   ARRAY['Drowsiness','Dizziness','Peripheral oedema'],
   ARRAY['Hypersensitivity to gabapentin']),
  ('Golimumab',
   ARRAY['Rheumatoid arthritis','Ankylosing spondylitis','Ulcerative colitis'],
   ARRAY['Infection','Injection site reaction','Raised liver enzymes'],
   ARRAY['Serious active infection','Untreated tuberculosis']),
  ('Hydrochlorothiazide',
   ARRAY['Hypertension','Oedema'],
   ARRAY['Hypokalaemia','Hyponatraemia','Hyperuricaemia','Photosensitivity'],
   ARRAY['Anuria','Sulfonamide hypersensitivity','Severe renal impairment']),
  ('Ibandronate',
   ARRAY['Postmenopausal osteoporosis'],
   ARRAY['Oesophageal irritation','Abdominal pain','Myalgia'],
   ARRAY['Oesophageal stricture','Inability to sit upright for 60 minutes','Hypocalcaemia']),
  ('Infliximab',
   ARRAY['Crohn disease','Rheumatoid arthritis','Ulcerative colitis'],
   ARRAY['Infusion reaction','Infection','Headache'],
   ARRAY['Serious active infection','Moderate to severe heart failure']),
  ('Isradipine',
   ARRAY['Hypertension'],
   ARRAY['Ankle oedema','Flushing','Palpitations'],
   ARRAY['Cardiogenic shock','Severe aortic stenosis']),
  ('Labetalol',
   ARRAY['Hypertension','Hypertension in pregnancy'],
   ARRAY['Postural hypotension','Fatigue','Scalp tingling'],
   ARRAY['Asthma','Severe bradycardia','Second or third degree heart block']),
  ('Leflunomide',
   ARRAY['Rheumatoid arthritis','Psoriatic arthritis'],
   ARRAY['Diarrhoea','Hepatotoxicity','Alopecia'],
   ARRAY['Pregnancy','Severe hepatic impairment','Severe immunodeficiency']),
  ('Linagliptin',
   ARRAY['Type 2 diabetes'],
   ARRAY['Nasopharyngitis','Headache','Pancreatitis'],
   ARRAY['Type 1 diabetes','Diabetic ketoacidosis']),
  ('Liraglutide',
   ARRAY['Type 2 diabetes','Weight management'],
   ARRAY['Nausea','Vomiting','Pancreatitis'],
   ARRAY['Personal or family history of medullary thyroid carcinoma','Multiple endocrine neoplasia type 2']),
  ('Lisinopril',
   ARRAY['Hypertension','Heart failure','Acute myocardial infarction'],
   ARRAY['Dry cough','Hyperkalaemia','Dizziness'],
   ARRAY['Pregnancy','Angioedema with a previous ACE inhibitor','Bilateral renal artery stenosis']),
  ('Methyldopa',
   ARRAY['Hypertension in pregnancy'],
   ARRAY['Sedation','Postural hypotension','Positive direct Coombs test'],
   ARRAY['Active hepatic disease','Phaeochromocytoma']),
  ('Metolazone',
   ARRAY['Oedema','Hypertension','Heart failure'],
   ARRAY['Hypokalaemia','Hyponatraemia','Dehydration'],
   ARRAY['Anuria','Hepatic coma']),
  ('Miglitol',
   ARRAY['Type 2 diabetes'],
   ARRAY['Flatulence','Diarrhoea','Abdominal pain'],
   ARRAY['Inflammatory bowel disease','Intestinal obstruction']),
  ('Minocycline',
   ARRAY['Acne vulgaris','Respiratory tract infection','Rickettsial infection'],
   ARRAY['Dizziness','Photosensitivity','Skin and mucosal pigmentation'],
   ARRAY['Pregnancy','Children under 12 years','Tetracycline hypersensitivity']),
  ('Nabumetone',
   ARRAY['Osteoarthritis','Rheumatoid arthritis'],
   ARRAY['Dyspepsia','Diarrhoea','Oedema'],
   ARRAY['Active peptic ulcer','Severe heart failure','Third trimester of pregnancy']),
  ('Nadolol',
   ARRAY['Hypertension','Angina'],
   ARRAY['Fatigue','Bradycardia','Cold extremities'],
   ARRAY['Asthma','Severe bradycardia','Second or third degree heart block']),
  ('Nateglinide',
   ARRAY['Type 2 diabetes'],
   ARRAY['Hypoglycaemia','Weight gain','Upper respiratory infection'],
   ARRAY['Type 1 diabetes','Diabetic ketoacidosis']),
  ('Nicardipine',
   ARRAY['Hypertension','Angina'],
   ARRAY['Flushing','Headache','Ankle oedema'],
   ARRAY['Advanced aortic stenosis','Cardiogenic shock']),
  ('Nisoldipine',
   ARRAY['Hypertension'],
   ARRAY['Ankle oedema','Headache','Flushing'],
   ARRAY['Cardiogenic shock','Severe aortic stenosis']),
  ('Paroxetine',
   ARRAY['Major depression','Panic disorder','Obsessive-compulsive disorder'],
   ARRAY['Nausea','Sexual dysfunction','Weight gain','Discontinuation syndrome'],
   ARRAY['Concurrent MAO inhibitor','Concurrent thioridazine']),
  ('Perindopril',
   ARRAY['Hypertension','Stable coronary artery disease'],
   ARRAY['Dry cough','Dizziness','Hyperkalaemia'],
   ARRAY['Pregnancy','Angioedema with a previous ACE inhibitor','Bilateral renal artery stenosis']),
  ('Pioglitazone',
   ARRAY['Type 2 diabetes'],
   ARRAY['Weight gain','Fluid retention','Increased fracture risk'],
   ARRAY['Heart failure','Active bladder cancer','Severe hepatic impairment']),
  ('Pramlintide',
   ARRAY['Type 1 diabetes as an insulin adjunct','Type 2 diabetes as an insulin adjunct'],
   ARRAY['Nausea','Hypoglycaemia when given with insulin','Anorexia'],
   ARRAY['Gastroparesis','Hypoglycaemia unawareness']),
  ('Propranolol',
   ARRAY['Hypertension','Angina','Migraine prophylaxis','Essential tremor'],
   ARRAY['Fatigue','Bradycardia','Cold extremities','Bronchospasm'],
   ARRAY['Asthma','Severe bradycardia','Second or third degree heart block']),
  ('Quinapril',
   ARRAY['Hypertension','Heart failure'],
   ARRAY['Dry cough','Dizziness','Hyperkalaemia'],
   ARRAY['Pregnancy','Angioedema with a previous ACE inhibitor','Bilateral renal artery stenosis']),
  ('Ramipril',
   ARRAY['Hypertension','Heart failure','Cardiovascular risk reduction'],
   ARRAY['Dry cough','Dizziness','Hyperkalaemia'],
   ARRAY['Pregnancy','Angioedema with a previous ACE inhibitor','Bilateral renal artery stenosis']),
  ('Risedronate',
   ARRAY['Osteoporosis','Paget disease of bone'],
   ARRAY['Oesophageal irritation','Abdominal pain','Musculoskeletal pain'],
   ARRAY['Oesophageal stricture','Inability to sit upright for 30 minutes','Hypocalcaemia']),
  ('Rituximab',
   ARRAY['Non-Hodgkin lymphoma','Chronic lymphocytic leukaemia','Rheumatoid arthritis'],
   ARRAY['Infusion reaction','Infection','Neutropenia'],
   ARRAY['Serious active infection','Severe heart failure']),
  ('Rosiglitazone',
   ARRAY['Type 2 diabetes'],
   ARRAY['Weight gain','Fluid retention','Anaemia'],
   ARRAY['Heart failure','Active hepatic disease']),
  ('Salsalate',
   ARRAY['Osteoarthritis','Rheumatoid arthritis'],
   ARRAY['Dyspepsia','Tinnitus','Gastrointestinal bleeding'],
   ARRAY['Salicylate hypersensitivity','Children with a viral illness']),
  ('Saxagliptin',
   ARRAY['Type 2 diabetes'],
   ARRAY['Upper respiratory infection','Headache','Pancreatitis'],
   ARRAY['Type 1 diabetes','Diabetic ketoacidosis']),
  ('Spironolactone',
   ARRAY['Chronic heart failure','Oedema','Primary hyperaldosteronism','Resistant hypertension'],
   ARRAY['Hyperkalaemia','Gynaecomastia','Menstrual irregularity'],
   ARRAY['Hyperkalaemia','Anuria','Severe renal impairment']),
  ('Sulindac',
   ARRAY['Osteoarthritis','Ankylosing spondylitis','Acute gout'],
   ARRAY['Dyspepsia','Rash','Gastrointestinal bleeding'],
   ARRAY['Active peptic ulcer','Aspirin-sensitive asthma','Third trimester of pregnancy']),
  ('Tacrolimus',
   ARRAY['Prophylaxis of transplant rejection'],
   ARRAY['Nephrotoxicity','Tremor','Hyperglycaemia','Hypertension'],
   ARRAY['Hypersensitivity to macrolides','Severe renal impairment']),
  ('Tocilizumab',
   ARRAY['Rheumatoid arthritis','Juvenile idiopathic arthritis'],
   ARRAY['Infection','Raised liver enzymes','Hyperlipidaemia'],
   ARRAY['Serious active infection','Neutropenia']),
  ('Tolmetin',
   ARRAY['Rheumatoid arthritis','Osteoarthritis'],
   ARRAY['Dyspepsia','Headache','Gastrointestinal bleeding'],
   ARRAY['Active peptic ulcer','Aspirin-sensitive asthma','Third trimester of pregnancy']),
  ('Torsemide',
   ARRAY['Oedema','Heart failure','Hypertension'],
   ARRAY['Hypokalaemia','Dehydration','Dizziness'],
   ARRAY['Anuria','Severe electrolyte depletion']),
  ('Trandolapril',
   ARRAY['Hypertension','Left ventricular dysfunction after myocardial infarction'],
   ARRAY['Dry cough','Dizziness','Hyperkalaemia'],
   ARRAY['Pregnancy','Angioedema with a previous ACE inhibitor','Bilateral renal artery stenosis']),
  ('Triamterene',
   ARRAY['Oedema','Hypertension'],
   ARRAY['Hyperkalaemia','Nausea','Raised serum creatinine'],
   ARRAY['Hyperkalaemia','Severe renal impairment','Anuria']),
  ('Valsartan',
   ARRAY['Hypertension','Chronic heart failure','Post-myocardial infarction'],
   ARRAY['Dizziness','Hyperkalaemia','Hypotension'],
   ARRAY['Pregnancy','Bilateral renal artery stenosis']),
  ('Venlafaxine',
   ARRAY['Major depression','Generalised anxiety disorder'],
   ARRAY['Nausea','Raised blood pressure','Insomnia','Discontinuation syndrome'],
   ARRAY['Concurrent MAO inhibitor','Uncontrolled hypertension']),
  ('Verapamil',
   ARRAY['Hypertension','Angina','Supraventricular tachycardia'],
   ARRAY['Constipation','Bradycardia','Ankle oedema'],
   ARRAY['Severe bradycardia','Systolic heart failure','Second or third degree heart block'])
) AS v(name, indications, side_effects, contraindications)
WHERE lower(d.name) = lower(v.name)
  -- Only fill the gap. A row that already has indications was authored
  -- elsewhere and is not this migration's to overwrite.
  AND (d.indications IS NULL OR cardinality(d.indications) = 0);
