-- Brands for the whole catalogue, each with the company that labels it.
--
-- 1174 brands across 681 of the 881 medicines, 1142 of them naming a
-- manufacturer. Never more than three for any one medicine, which is both the
-- brief and about right: enough that recognising the brand is a real decision,
-- few enough that it is not a memory test.
--
-- Brand and company both come from the FDA National Drug Code directory, which
-- lists every marketed product with its brand_name and labeler_name. Nothing
-- here is invented.
--
-- Two filters did the work. A listing whose "brand" restates the generic -
-- "Metformin Hydrochloride", "Atorvastatin Calcium" - is not a brand and
-- teaches nothing at the brand step; the same test also drops the combination
-- listings ("Glyburide and Metformin"), which are most of what the registry
-- returns for a genericised drug. Each surviving brand is then confirmed
-- against a single-ingredient product, because a combination brand like Caduet
-- names neither of its ingredients and would otherwise pass.
--
-- Two things to know before this is shown to a client:
--
-- The company is the FDA *labeler* - whoever puts their name on that package.
-- Usually that is the originator, but for widely distributed products it can be
-- a repackager, so Eliquis reads as A-S Medication Solutions rather than
-- Bristol-Myers Squibb. Right about the box, not always about the maker.
--
-- 195 medicines have no brand at all. That is the registry being accurate
-- rather than a gap: metformin has no currently marketed US brand, Glucophage
-- having been discontinued there. Inventing one would have been worse.
--
-- The 37 gameplay medicines keep their hand-curated international brands
-- (Panadol/Haleon, Risek/Getz) - those were chosen for the markets this product
-- trains for and are better than anything the US registry would give.

INSERT INTO public.drug_brands (drug_id, brand, market, manufacturer)
SELECT d.id, v.brand, v.market, v.manufacturer
FROM (VALUES
  ('Abatacept', 'Orencia', 'US', 'E.R. Squibb & Sons, L.L.C.'),
  ('Abciximab', 'ReoPro', 'US', NULL),
  ('Acarbose', 'Precose', 'US', NULL),
  ('Acebutolol', 'Sectral', 'US', NULL),
  ('Acetaminophen', 'Pain Relief', 'US', 'AAA Pharmaceutical, Inc.'),
  ('Acetaminophen', 'Pain Relief Extra Strength', 'US', 'CHAIN DRUG MARKETING ASSOCIATION, INC.'),
  ('Acetaminophen', 'Pain Reliever', 'US', 'WALGREEN CO.'),
  ('Acetic Acid', 'Aceticum Acidum', 'US', 'Boiron'),
  ('Acetylcysteine', 'Acetadote', 'US', 'Cumberland Pharmaceuticals Inc.'),
  ('Aclidinium', 'Tudorza Pressair', 'US', 'Covis Pharma US, Inc'),
  ('Activated Charcoal', 'Actidose', 'US', 'Padagis US LLC'),
  ('Activated Charcoal', 'Actidose Aqua', 'US', 'Padagis US LLC'),
  ('Activated Charcoal', 'Carbo Vegetabilis', 'US', 'Boiron'),
  ('Acyclovir', 'Avaclyr', 'US', 'Fera Pharmaceuticals, LLC'),
  ('Acyclovir', 'Zovirax', 'US', 'Bausch Health US, LLC'),
  ('Adalimumab', 'Humira', 'US', NULL),
  ('Adalimumab-Adaz', 'Hyrimoz', 'US', 'Sandoz Inc'),
  ('Adalimumab-Aqvh', 'Yusimry', 'US', 'Meitheal Pharmaceuticals Inc.'),
  ('Adalimumab-Atto', 'Amjevita', 'US', 'Amgen, Inc'),
  ('Adalimumab-Bwwd', 'Hadlima', 'US', 'Organon LLC'),
  ('Adapalene', 'Curist Acne Relief', 'US', 'Little Pharma, Inc.'),
  ('Adapalene', 'Effaclar', 'US', 'LOreal USA Products Inc'),
  ('Adapalene', 'Panoxyl', 'US', 'CROWN LABORATORIES'),
  ('Ado-Trastuzumab Emtansine', 'Kadcyla', 'US', 'Genentech, Inc.'),
  ('Agalsidase Beta', 'Fabrazyme', 'US', 'Genzyme Corporation'),
  ('Albuterol', 'Proair Digihaler', 'US', 'Teva Respiratory, LLC'),
  ('Albuterol', 'Proair Respiclick', 'US', 'Teva Respiratory, LLC'),
  ('Albuterol', 'Ventolin Hfa', 'US', 'NuCare Pharmaceuticals,Inc.'),
  ('Alcaftadine', 'Lastacaft', 'US', 'Allergan, Inc.'),
  ('Alemtuzumab', 'Campath', 'US', 'Genzyme Corporation'),
  ('Alemtuzumab', 'Lemtrada', 'US', 'Genzyme Corporation'),
  ('Alendronate', 'Binosto', 'US', 'Radius Health, Inc.'),
  ('Alendronate', 'Fosamax', 'US', 'Organon LLC'),
  ('Alglucosidase Alfa', 'Lumizyme', 'US', 'Genzyme Corporation'),
  ('Alirocumab', 'Praluent', 'US', 'Regeneron Pharmaceuticals, Inc.'),
  ('Allopurinol', 'Aloprim', 'US', 'Mylan Institutional LLC'),
  ('Alprazolam', 'Xanax', 'US', 'Viatris Specialty LLC'),
  ('Alprazolam', 'Xanax Xr', 'US', 'Viatris Specialty LLC'),
  ('Alprostadil', 'Caverject', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Alprostadil', 'Caverject Impulse', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Alprostadil', 'Edex', 'US', 'Endo USA, Inc.'),
  ('Alteplase', 'Cathflo Activase', 'US', 'Genentech, Inc.'),
  ('Aluminium Hydroxide', 'AlternaGEL', 'GLOBAL', 'Johnson & Johnson'),
  ('Aluminium Hydroxide', 'Alu-Cap', 'GLOBAL', 'Mylan'),
  ('Aluminium Hydroxide', 'Amphojel', 'GLOBAL', 'Pfizer'),
  ('Amantadine', 'Gocovri', 'US', 'Supernus Pharmaceuticals'),
  ('Amifostine', 'Ethyol', 'US', 'Legacy Pharma USA Inc.'),
  ('Amikacin', 'Arikayce', 'US', 'Insmed Incorporated'),
  ('Amiloride', 'Midamor', 'US', NULL),
  ('Amiodarone', 'Nexterone', 'US', 'Baxter Healthcare Corporation'),
  ('Amiodarone', 'Pacerone', 'US', 'Upsher-Smith Laboratories, LLC'),
  ('Amlodipine', 'Amlodac', 'GLOBAL', 'Zydus'),
  ('Amlodipine', 'Amlong', 'GLOBAL', 'Micro Labs'),
  ('Amlodipine', 'Norvasc', 'GLOBAL', 'Pfizer'),
  ('Amoxicillin', 'Amoxil', 'GLOBAL', 'GSK'),
  ('Amoxicillin', 'Moxatag', 'GLOBAL', 'Pragma Pharmaceuticals'),
  ('Amoxicillin', 'Ospamox', 'GLOBAL', 'Sandoz'),
  ('Amphetamine', 'Adzenys Xr-Odt', 'US', 'Neos Therapeutics Brands, LLC'),
  ('Amphetamine', 'Dyanavel Xr', 'US', 'NextWave Pharmaceuticals, Inc'),
  ('Amphetamine', 'Evekeo', 'US', 'Azurity Pharmaceuticals, Inc.'),
  ('Amyl Nitrite', 'Amyl Nitrosum', 'US', 'Boiron'),
  ('Anakinra', 'Kineret', 'US', 'Swedish Orphan Biovitrum AB (publ)'),
  ('Anastrozole', 'Arimidex', 'US', 'ANI Pharmaceuticals, Inc.'),
  ('Anidulafungin', 'Eraxis', 'US', 'Roerig'),
  ('Anifrolumab-Fnia', 'Saphnelo', 'US', 'AstraZeneca Pharmaceuticals LP'),
  ('Ansuvimab', 'Ebanga', 'US', 'Emergent BioDefense Operations Lansing LLC'),
  ('Antifungal', 'Gerigentle Miconazole Nitrate', 'US', 'GERI-GENTLE CORPORATION'),
  ('Antifungal', 'Kerova Clotrimazole', 'US', 'Guangzhou Bixiaoyu Trading Co., Ltd.'),
  ('Antifungal', 'Miconazole Nitrate', 'US', 'Premier Brands of America Inc.'),
  ('Apixaban', 'Eliquis', 'US', 'A-S Medication Solutions'),
  ('Apixaban', 'Eliquis Sprinkle', 'US', 'E.R. Squibb & Sons, L.L.C.'),
  ('Apomorphine', 'Apokyn', 'US', 'MDD US Operations, LLC'),
  ('Apomorphine', 'Onapgo', 'US', 'MDD US Operations, LLC, a subsidiary of Supernus Pharmaceuticals, Inc'),
  ('Aprepitant', 'Aponvie', 'US', 'Heron Therapeutics, Inc.'),
  ('Aprepitant', 'Cinvanti', 'US', 'Heron Therapeutics, Inc.'),
  ('Aprepitant', 'Emend', 'US', 'Merck Sharp & Dohme LLC'),
  ('Aripiprazole', 'Abilify', 'US', 'Otsuka America Pharmaceutical, Inc.'),
  ('Aripiprazole', 'Abilify Asimtufii', 'US', 'Otsuka America Pharmaceutical, Inc'),
  ('Aripiprazole', 'Opipza', 'US', 'Carwin Pharmaceutical Associates, LLC'),
  ('Armodafinil', 'Nuvigil', 'US', 'Golden State Medical Supply, Inc.'),
  ('Arsenic Trioxide', 'Arsenicum Album', 'US', 'Boiron'),
  ('Asenapine', 'Saphris', 'US', 'Allergan, Inc.'),
  ('Asenapine', 'Secuado', 'US', 'Noven Therapeutics, LLC'),
  ('Asfotase Alfa', 'Strensiq', 'US', 'Alexion Pharmaceuticals, Inc.'),
  ('Atenolol', 'Blokium', 'GLOBAL', 'Menarini'),
  ('Atenolol', 'Tenolol', 'GLOBAL', 'Ipca Laboratories'),
  ('Atenolol', 'Tenormin', 'GLOBAL', 'Atnahs Pharma'),
  ('Atezolizumab', 'Tecentriq', 'US', 'Genentech, Inc.'),
  ('Atomoxetine', 'Atoncy', 'US', 'Validus Pharmaceuticals LLC'),
  ('Atomoxetine', 'Strattera', 'US', 'Eli Lilly and Company'),
  ('Atorvastatin', 'Lipitor', 'US', 'Viatris Specialty LLC'),
  ('Atovaquone', 'Mepron', 'US', 'GlaxoSmithKline LLC'),
  ('Atropine', 'Atropen Auto-Injector', 'US', 'Meridian Medical Technologies LLC'),
  ('Axatilimab-Csfr', 'Niktimvo', 'US', 'Incyte Corporation'),
  ('Azacitidine', 'Onureg', 'US', 'Celgene Corporation'),
  ('Azacitidine', 'Vidaza', 'US', 'Celgene Corporation'),
  ('Azathioprine', 'Azasan', 'US', 'Salix Pharmaceuticals'),
  ('Azathioprine', 'Imuran', 'US', 'Sebela Pharmaceuticals Inc.'),
  ('Azelaic Acid', 'Azelex', 'US', 'Almirall, LLC'),
  ('Azelaic Acid', 'Finacea Foam', 'US', 'LEO Pharma Inc.'),
  ('Azelastine', 'Astepro Allergy', 'US', 'Bayer HealthCare LLC.'),
  ('Azelastine', 'Children Astepro Allergy', 'US', 'Bayer HealthCare LLC.'),
  ('Azithromycin', 'Azomax', 'GLOBAL', 'Sami Pharmaceuticals'),
  ('Azithromycin', 'Zetro', 'GLOBAL', 'Getz Pharma'),
  ('Azithromycin', 'Zithromax', 'GLOBAL', 'Pfizer'),
  ('Bacitracin', 'Antibiotic', 'US', 'Topco Associates LLC'),
  ('Bacitracin Zinc', 'First Aid Antibiotic', 'US', 'Medline Industries, LP'),
  ('Baclofen', 'Fleqsuvy', 'US', 'Azurity Pharmaceuticals, Inc.'),
  ('Baclofen', 'Gablofen', 'US', 'Piramal Critical Care Inc'),
  ('Baclofen', 'Lyvispah', 'US', 'Amneal Pharmaceuticals LLC'),
  ('Basiliximab', 'Simulect', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Beclomethasone', 'Qnasl', 'US', 'Teva Respiratory, LLC'),
  ('Belatacept', 'Nulojix', 'US', 'E.R. Squibb & Sons, L.L.C.'),
  ('Belimumab', 'Benlysta', 'US', 'GlaxoSmithKline LLC'),
  ('Benazepril', 'Lotensin', 'US', 'Validus Pharmaceuticals LLC'),
  ('Bendamustine', 'Belrapzo', 'US', 'Eagle Pharmaceuticals, Inc'),
  ('Bendamustine', 'Treanda', 'US', 'Cephalon, LLC'),
  ('Bendamustine', 'Vivimusta', 'US', 'Azurity Pharmaceuticals, Inc.'),
  ('Benralizumab', 'Fasenra', 'US', 'AstraZeneca Pharmaceuticals LP'),
  ('Benzalkonium', 'Antibacterial', 'US', 'Sante Manufcaturing Inc'),
  ('Benzalkonium', 'Hand Wash', 'US', 'Meijer, Inc.'),
  ('Benzalkonium', 'Moisturizing Antibacterial', 'US', 'Walmart Inc.'),
  ('Benzocaine', 'Bencocaine Topical Anesthetic', 'US', 'Benco Dental'),
  ('Benzocaine', 'Candee Caine Topical Anesthetic', 'US', 'American Medical & Hospital Supply Co., Inc.'),
  ('Benzocaine', 'Hurricaine Topical Anesthetic', 'US', 'Beutlich Pharmaceuticals, LLC'),
  ('Benzoyl Peroxide', 'Acne Treatment', 'US', 'Rite Aid Corporation'),
  ('Benzoyl Peroxide', 'Bp Wash', 'US', 'CINTEX SERVICES, LLC'),
  ('Benzoyl Peroxide', 'Panoxyl', 'US', 'Crown Laboratories'),
  ('Besifloxacin', 'Besivance', 'US', 'Bausch & Lomb Americas Inc.'),
  ('Betamethasone', 'Diprolene', 'US', 'Organon LLC'),
  ('Betaxolol', 'Betoptic S', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Bevacizumab', 'Avastin', 'US', 'Genentech, Inc.'),
  ('Bevacizumab-Adcd', 'Vegzelma', 'US', 'CELLTRION USA, Inc.'),
  ('Bevacizumab-Awwb', 'Mvasi', 'US', 'Amgen, Inc'),
  ('Bevacizumab-Bvzr', 'Zirabev', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Bevacizumab-Maly', 'Alymsys', 'US', 'Amneal Pharmaceuticals LLC'),
  ('Bimatoprost', 'Durysta', 'US', 'Allergan, Inc.'),
  ('Bimatoprost', 'Latisse', 'US', 'Allergan, Inc.'),
  ('Bimatoprost', 'Lumigan', 'US', 'Allergan, Inc.'),
  ('Bimekizumab', 'Bimzelx', 'US', 'UCB, Inc.'),
  ('Bisacodyl', 'Correctol', 'GLOBAL', 'Bayer'),
  ('Bisacodyl', 'Dulcolax', 'GLOBAL', 'Sanofi'),
  ('Bisacodyl', 'Fleet Bisacodyl', 'GLOBAL', 'Fleet Laboratories'),
  ('Bisoprolol', 'Zebeta', 'US', NULL),
  ('Boric Acid', 'V-Bella', 'US', 'U.S. PHARMACEUTICAL CORPORATION'),
  ('Bortezomib', 'Boruzu', 'US', 'Amneal Pharmaceuticals LLC'),
  ('Bortezomib', 'Velcade', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Brimonidine', 'Alphagan P', 'US', 'Allergan, Inc.'),
  ('Brimonidine', 'Lumify Preservative Free Eye Drops', 'US', 'Bausch & Lomb Incorporated'),
  ('Brimonidine', 'Lumify Redness Reliever Eye Drops', 'US', 'Bausch & Lomb Incorporated'),
  ('Brinzolamide', 'Azopt', 'US', 'Sandoz Inc'),
  ('Brivaracetam', 'Briviact', 'US', 'UCB, Inc.'),
  ('Brivaracetam', 'Briviact', 'US', 'UCB, Inc.'),
  ('Brodalumab', 'Siliq', 'US', 'Bausch Health US LLC'),
  ('Bromfenac', 'Bromsite 0.075%', 'US', 'Sun Pharmaceutical Industries, Inc.'),
  ('Bromfenac', 'Prolensa', 'US', 'Bausch & Lomb Incorporated'),
  ('Bromocriptine', 'Cycloset', 'US', 'Avvisto Therapeutics LLC'),
  ('Budesonide', 'Budecort', 'GLOBAL', 'Cipla'),
  ('Budesonide', 'Entocort', 'GLOBAL', 'Tillotts Pharma'),
  ('Budesonide', 'Pulmicort', 'GLOBAL', 'AstraZeneca'),
  ('Bulevirtide', 'Hepcludex', 'US', 'Gilead Sciences, Inc.'),
  ('Bumetanide', 'Bumex', 'US', 'Validus Pharmaceuticals LLC'),
  ('Bumetanide', 'Enbumyst', 'US', 'Corstasis USA LLC'),
  ('Bupivacaine', 'Marcaine', 'US', 'Hospira, Inc.'),
  ('Bupivacaine', 'Sensorcaine', 'US', 'Fresenius Kabi USA, LLC'),
  ('Bupivacaine', 'Sensorcaine Mpf', 'US', 'Fresenius Kabi USA, LLC'),
  ('Buprenorphine', 'Belbuca', 'US', 'BioDelivery Sciences International Inc'),
  ('Buprenorphine', 'Brixadi', 'US', 'Braeburn Inc.'),
  ('Buprenorphine', 'Butrans', 'US', 'Knoa Pharma LLC'),
  ('Bupropion', 'Aplenzin', 'US', 'Bausch Health US, LLC'),
  ('Bupropion', 'Wellbutrin Sr', 'US', 'GlaxoSmithKline LLC'),
  ('Bupropion', 'Wellbutrin Xl', 'US', 'Bausch Health US LLC'),
  ('Busulfan', 'Myleran', 'US', 'Waylis Therapeutics LLC'),
  ('Butenafine', 'Athletes Foot', 'US', 'Rite Aid Corporation'),
  ('Butenafine', 'Athletes Foot Ultra', 'US', 'H E B'),
  ('Butenafine', 'Jock Itch', 'US', 'Sun Pharmaceutical Industries, Inc.'),
  ('Butoconazole', 'Gynazole 1', 'US', 'Padagis Israel Pharmaceuticals Ltd'),
  ('Caffeine', 'Stay Awake', 'US', 'ARMY AND AIR FORCE EXCHANGE SERVICE'),
  ('Calcarea Phosphorica', 'Bm Calc Phos', 'US', 'BM Private Limited'),
  ('Calcarea Phosphorica', 'Bm Calc Phos Icing Sugar', 'US', 'BM Private Limited'),
  ('Calcarea Sulphurica', 'Bestmade Natural Products Calc Sulph 8X', 'US', 'Bestmade Natural Products'),
  ('Calcarea Sulphurica', 'Bm Calc Sulph', 'US', 'BM Private Limited'),
  ('Calcipotriene', 'Calcitrene', 'US', 'Sun Pharmaceutical Industries, Inc.'),
  ('Calcipotriene', 'Pellix', 'US', 'Perfero Pharma, Inc.'),
  ('Calcipotriene', 'Sorilux', 'US', 'Mayne Pharma'),
  ('Calcitriol', 'Vectical', 'US', 'Galderma Laboratories, L.P.'),
  ('Calcium Carbonate', 'Caltrate', 'GLOBAL', 'Haleon'),
  ('Calcium Carbonate', 'Rennie', 'GLOBAL', 'Bayer'),
  ('Calcium Carbonate', 'Tums', 'GLOBAL', 'Haleon'),
  ('Calcium Polycarbophil', 'Fiber Caplets', 'US', 'THE KROGER CO.'),
  ('Calcium Polycarbophil', 'Fiber Lax', 'US', 'Rugby Laboratories'),
  ('Calcium Polycarbophil', 'Fiber Laxative', 'US', 'Geri-Care Pharmaceutical Corp'),
  ('Candesartan', 'Atacand', 'US', NULL),
  ('Capecitabine', 'Xeloda', 'US', 'H2-Pharma, LLC'),
  ('Captopril', 'Capoten', 'US', NULL),
  ('Carbachol', 'Miostat', 'US', 'Alcon Laboratories, Inc.'),
  ('Carbamazepine', 'Carbatrol', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Carbamazepine', 'Equetro', 'US', 'Validus Pharmaceuticals LLC'),
  ('Carbamazepine', 'Tegretol Xr', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Carboplatin', 'Kyxata', 'US', 'Avyxa Pharma, LLC'),
  ('Carboprost', 'Hemabate', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Carfilzomib', 'Kyprolis', 'US', 'Onyx Pharmaceuticals, Inc.'),
  ('Carisoprodol', 'Soma', 'US', 'Viatris Specialty LLC'),
  ('Carvedilol', 'Coreg', 'US', 'Waylis Therapeutics LLC'),
  ('Carvedilol', 'Coreg Cr', 'US', 'Waylis Therapeutics LLC'),
  ('Caspofungin', 'Cancidas', 'US', 'Merck Sharp & Dohme LLC'),
  ('Cefotetan', 'Cefotan', 'US', 'PAI Holdings, LLC dba PAI Pharma'),
  ('Ceftazidime', 'Tazicef', 'US', 'Hospira, Inc.'),
  ('Celecoxib', 'Celebrex', 'US', 'Viatris Specialty LLC'),
  ('Celecoxib', 'Vyscoxa', 'US', 'Carwin Pharmaceutical Associates, LLC'),
  ('Cenegermin-Bkbj', 'Oxervate', 'US', 'Domp farmaceutici S.p.A.'),
  ('Certolizumab', 'Cimzia', 'US', NULL),
  ('Certolizumab Pegol', 'Cimzia', 'US', 'UCB, Inc.'),
  ('Cetirizine', 'Alerid', 'GLOBAL', 'Cipla'),
  ('Cetirizine', 'Reactine', 'GLOBAL', 'Bayer'),
  ('Cetirizine', 'Zyrtec', 'GLOBAL', 'Kenvue'),
  ('Cetylpyridinium', 'Antigingivitis/Antiplaque', 'US', 'Topco Associates LLC'),
  ('Cetylpyridinium', 'Antiseptic', 'US', 'Your Military Exchanges'),
  ('Cetylpyridinium', 'Cloveden 100 Times Higher Concentrated', 'US', 'DONG IL PHARMS CO.,LTD'),
  ('Chlorhexidine', 'Antiseptic Skin Cleanser', 'US', 'McKesson Medical-Surgical'),
  ('Chlorhexidine', 'Bactoshield Chg', 'US', 'SC Johnson Professional USA, Inc.'),
  ('Chlorhexidine', 'Hibiclens', 'US', 'Molnlycke Health Care'),
  ('Chloroprocaine Hydrochloride Ophthalmic', 'Iheezo', 'US', 'Harrow Eye, LLC'),
  ('Chlorothiazide', 'Diuril', 'US', 'Salix Pharmaceuticals, Inc'),
  ('Chlorpheniramine', 'Allercalm', 'GLOBAL', 'Sami Pharmaceuticals'),
  ('Chlorpheniramine', 'Chlor-Trimeton', 'GLOBAL', 'Bayer'),
  ('Chlorpheniramine', 'Piriton', 'GLOBAL', 'Haleon'),
  ('Chlorthalidone', 'Hemiclor', 'US', 'Ingenus Pharmaceuticals, LLC'),
  ('Chlorthalidone', 'Thalitone', 'US', 'Casper Pharma LLC'),
  ('Ciclesonide', 'Alvesco', 'US', 'Covis Pharma US, Inc'),
  ('Ciclesonide', 'Omnaris', 'US', 'Covis Pharma US, Inc'),
  ('Cimetidine', 'Acid Controller', 'US', 'CVS WOONSOCKET PRESCRIPTION CENTER, INCORPORATED'),
  ('Cimetidine', 'Basic Care Acid Reducer', 'US', 'Amazon.com Services LLC'),
  ('Cimetidine', 'Tagamet', 'US', 'Medtech Products Inc.'),
  ('Cinacalcet', 'Sensipar', 'US', 'Amgen Inc'),
  ('Ciprofloxacin', 'Ciloxan', 'US', 'Sandoz Inc'),
  ('Citalopram', 'Celexa', 'US', 'Allergan, Inc.'),
  ('Cladribine', 'Mavenclad', 'US', 'EMD Serono, Inc.'),
  ('Clarithromycin', 'Biaxin', 'GLOBAL', 'AbbVie'),
  ('Clarithromycin', 'Claritek', 'GLOBAL', 'Getz Pharma'),
  ('Clarithromycin', 'Klaricid', 'GLOBAL', 'Abbott'),
  ('Clesrovimab', 'Enflonsia', 'US', 'Merck Sharp & Dohme LLC'),
  ('Clindamycin', 'Cleocin', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Clindamycin', 'Cleocin Hydrochloride', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Clindamycin', 'Cleocin Phosphate', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Clobazam', 'Onfi', 'US', 'Lundbeck Pharmaceuticals LLC'),
  ('Clobazam', 'Sympazan', 'US', 'Aquestive Therapeutics'),
  ('Clobetasol', 'Byqlovi', 'US', 'Harrow Eye, LLC'),
  ('Clobetasol', 'Clodan', 'US', 'Medimetriks Pharmaceuticals'),
  ('Clobetasol', 'Impoyz', 'US', 'Primus Pharmaceuticals, Inc.'),
  ('Clomipramine', 'Anafranil', 'US', 'SpecGx LLC'),
  ('Clonazepam', 'Klonopin', 'US', 'H2-Pharma, LLC'),
  ('Clonidine', 'Duraclon', 'US', 'Mylan Institutional LLC'),
  ('Clonidine', 'Javadin', 'US', 'Azurity Pharmaceuticals, Inc.'),
  ('Clonidine', 'Nexiclon Xr', 'US', 'Rosemont Pharmaceuticals LLC'),
  ('Clonidine Transdermal System', 'Catapres-Tts-1', 'US', 'Technomed Inc.'),
  ('Clonidine Transdermal System', 'Catapres-Tts-2', 'US', 'Technomed Inc.'),
  ('Clonidine Transdermal System', 'Catapres-Tts-3', 'US', 'Technomed Inc.'),
  ('Clopidogrel', 'Plavix', 'US', 'Sanofi-Aventis U.S. LLC'),
  ('Clotrimazole', 'Antifungal', 'US', 'Encube Ethicals, Inc.'),
  ('Clotrimazole', 'Fortinia', 'US', 'The Podiatree Company'),
  ('Clotrimazole', 'Lotrimin', 'US', 'Bayer HealthCare LLC'),
  ('Clotrimazole cream', 'Candid', 'GLOBAL', 'Glenmark'),
  ('Clotrimazole cream', 'Canesten', 'GLOBAL', 'Bayer'),
  ('Clotrimazole cream', 'Lotrimin AF', 'GLOBAL', 'Bayer'),
  ('Clozapine', 'Clozaril', 'US', 'HLS Therapeutics (USA), Inc.'),
  ('Clozapine', 'Versacloz', 'US', 'TruPharma LLC'),
  ('Co-amoxiclav', 'Amoclan', 'GLOBAL', 'Hikma'),
  ('Co-amoxiclav', 'Augmentin', 'GLOBAL', 'GSK'),
  ('Co-amoxiclav', 'Calamox', 'GLOBAL', 'Sami Pharmaceuticals'),
  ('Cocaine', 'Goprelto', 'US', 'LXO US Inc.'),
  ('Colchicine', 'Colcrys', 'US', 'Proficient Rx LP'),
  ('Colchicine', 'Gloperba', 'US', 'Scilex Pharmaceuticals Inc.'),
  ('Colchicine', 'Mitigare', 'US', 'Hikma Specialty USA Inc.'),
  ('Colesevelam', 'Welchol', 'US', NULL),
  ('Colistimethate', 'Coly-Mycin M', 'US', 'Par Health USA, LLC'),
  ('Concizumab', 'Alhemo', 'US', 'Novo Nordisk'),
  ('Conjugated Estrogens', 'Premarin', 'US', 'Wyeth Pharmaceuticals LLC, a subsidiary of Pfizer Inc.'),
  ('Conjugated Estrogens', 'Premarin Vaginal', 'US', 'Wyeth Pharmaceuticals LLC, a subsidiary of Pfizer Inc.'),
  ('Cromolyn', 'Gastrocrom', 'US', 'Viatris Specialty LLC'),
  ('Cromolyn', 'Nasalcrom', 'US', 'Prestige Brands Holdings, Inc.'),
  ('Crovalimab', 'Piasky', 'US', 'Genentech, Inc.'),
  ('Cyclobenzaprine', 'Amrix', 'US', 'Cephalon, LLC'),
  ('Cyclobenzaprine', 'Fexmid', 'US', 'Rising Pharma Holdings, Inc.'),
  ('Cyclobenzaprine', 'Tonmya', 'US', 'Tonix Medicines, Inc.'),
  ('Cyclopentolate', 'Cyclogyl', 'US', 'Alcon Laboratories, Inc.'),
  ('Cyclophosphamide', 'Frindovyx', 'US', 'Avyxa Pharma, LLC'),
  ('Cyclosporine', 'Cequa', 'US', 'Sun Pharmaceutical Industries, Inc.'),
  ('Cyclosporine', 'Neoral', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Cyclosporine', 'Sandimmune', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Cyclosporine Ophthalmic', 'Vevye', 'US', 'Harrow Eye, LLC'),
  ('Cysteamine', 'Cystagon', 'US', 'Mylan Pharmaceuticals Inc.'),
  ('Cysteamine', 'Cystaran', 'US', 'Leadiant Biosciences, Inc.'),
  ('Cysteamine', 'Procysbi', 'US', 'Horizon Therapeutics USA, Inc.'),
  ('Dabigatran Etexilate', 'Pradaxa', 'US', 'Boehringer Ingelheim Pharmaceuticals, Inc.'),
  ('Dalbavancin', 'Dalvance', 'US', 'Allergan, Inc.'),
  ('Dalteparin', 'Fragmin', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Dapagliflozin', 'Farxiga', 'US', 'AstraZeneca Pharmaceuticals LP'),
  ('Dapsone', 'Aczone', 'US', 'Allergan, Inc.'),
  ('Darbepoetin Alfa', 'Aranesp', 'US', 'Amgen, Inc'),
  ('Dasatinib', 'Phyrago', 'US', 'Cycle Pharmaceuticals Ltd'),
  ('Dasatinib', 'Sprycel', 'US', 'E.R. Squibb & Sons, L.L.C.'),
  ('Deferasirox', 'Deferasorox', 'US', 'Novadoz Pharmaceuticals LLC'),
  ('Deferasirox', 'Exjade', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Deferasirox', 'Jadenu', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Deferoxamine', 'Desferal', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Deflazacort', 'Emflaza', 'US', 'PTC Therapeutics, Inc.'),
  ('Deflazacort', 'Jaythari', 'US', 'Doppel Farmaceutici S.r.l.'),
  ('Deflazacort', 'Kymbee', 'US', 'Upsher-Smith Laboratories, LLC'),
  ('Deoxycholic Acid', 'Kybella', 'US', 'Kythera Biopharmaceuticals Inc.'),
  ('Desflurane', 'Suprane', 'US', 'Baxter Healthcare Corporation'),
  ('Desipramine', 'Norpramin', 'US', 'Validus Pharmaceuticals LLC'),
  ('Desoximetasone', 'Topicort', 'US', 'Sun Pharmaceutical Industries, Inc.'),
  ('Desvenlafaxine', 'Pristiq Extended-Release', 'US', 'Wyeth Pharmaceuticals LLC, a subsidiary of Pfizer Inc.'),
  ('Dexamethasone', 'Dextenza', 'US', 'Ocular Therapeutix, Inc.'),
  ('Dexamethasone', 'Dmt Suik', 'US', 'Asclemed USA, Inc.'),
  ('Dexamethasone', 'Hemady', 'US', 'Edenbridge Pharmaceuticals LLC.'),
  ('Dexlansoprazole', 'Dexilant', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Dexmedetomidine', 'Igalmi', 'US', 'BioXcel Therapeutics, Inc.'),
  ('Dexmedetomidine', 'Precedex', 'US', 'Hospira, Inc.'),
  ('Dexmethylphenidate', 'Focalin', 'US', 'Sandoz Inc'),
  ('Dexmethylphenidate', 'Focalin Xr', 'US', 'Sandoz Inc'),
  ('Dextroamphetamine', 'Dexedrine Spansule', 'US', 'Amneal Pharmaceuticals LLC'),
  ('Dextroamphetamine', 'Xelstrym', 'US', 'Noven Therapeutics, LLC'),
  ('Dextroamphetamine', 'Zenzedi', 'US', 'Azurity Pharmaceuticals, Inc.'),
  ('Diazepam', 'Valium', 'US', 'Waylis Therapuetics LLC'),
  ('Diazepam', 'Valtoco', 'US', 'Neurelis, Inc'),
  ('Dibucaine', 'Cvs Topical Analgesic Hemorrhoidal', 'US', 'CVS PHARMACY,INC'),
  ('Dibucaine', 'Cvs Topical Anesthetic Hemorrhoidal', 'US', 'CVS PHARMACY, INC'),
  ('Diclofenac', 'Cataflam', 'GLOBAL', 'Novartis'),
  ('Diclofenac', 'Dicloran', 'GLOBAL', 'Sami Pharmaceuticals'),
  ('Diclofenac', 'Voltaren', 'GLOBAL', 'Novartis'),
  ('Diclofenac Epolamine', 'Flector', 'US', 'IBSA Pharma Inc.'),
  ('Diclofenac Epolamine', 'Licart', 'US', 'IBSA Pharma Inc.'),
  ('Diflorasone Diacetate', 'Psorcon', 'US', 'Sun Pharmaceutical Industries, Inc.'),
  ('Difluprednate', 'Durezol', 'US', 'Sandoz Inc'),
  ('Digoxin', 'Lanoxin', 'US', 'Covis Pharma US, Inc'),
  ('Diltiazem', 'Cardizem La', 'US', 'Bausch Health US LLC'),
  ('Diltiazem', 'Cartia Xt', 'US', 'Actavis Pharma, Inc.'),
  ('Diltiazem', 'Tiadylt Er', 'US', 'Zydus Pharmaceuticals (USA) Inc.'),
  ('Dimenhydrinate', 'Dramamine For Kids', 'US', 'Medtech Products Inc.'),
  ('Dimenhydrinate', 'Motion Sickness', 'US', 'Strategic Sourcing Services LLC'),
  ('Dimenhydrinate', 'Motion Sickness Relief', 'US', 'Walgreen Company'),
  ('Dinoprostone', 'Cervidil', 'US', 'Ferring Pharmaceuticals Inc.'),
  ('Dinoprostone', 'Prepidil', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Diphenhydramine', 'Benadryl', 'GLOBAL', 'Kenvue'),
  ('Diphenhydramine', 'Nytol', 'GLOBAL', 'Vitabiotics'),
  ('Diphenhydramine', 'ZzzQuil', 'GLOBAL', 'Procter & Gamble'),
  ('Docetaxel', 'Beizray', 'US', 'Zydus Pharmaceuticals USA Inc.'),
  ('Docetaxel', 'Docivyx', 'US', 'Avyxa Pharma, LLC'),
  ('Docosanol', 'Cold Sore Fever Blister', 'US', 'H E B'),
  ('Docosanol', 'Cold Sore Fever Blister Treatment', 'US', 'Dolgencorp, Inc. (DOLLAR GENERAL & REXALL)'),
  ('Docosanol', 'Cold Sore Treatment', 'US', 'P & L Development, LLC'),
  ('Docusate', 'Stool Softener', 'US', 'HEB'),
  ('Docusate', 'Stool Softener Extra Strength', 'US', 'CVS Pharmacy'),
  ('Docusate', 'Stool Softener Laxative', 'US', 'CVS Pharmacy'),
  ('Dofetilide', 'Tikosyn', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Domperidone', 'Domel', 'GLOBAL', 'Sami Pharmaceuticals'),
  ('Domperidone', 'Motilium', 'GLOBAL', 'Janssen'),
  ('Domperidone', 'Motinorm', 'GLOBAL', 'Sun Pharma'),
  ('Donepezil', 'Aricept', 'US', 'Eisai Inc.'),
  ('Doxazosin', 'Cardura', 'US', 'Viatris Specialty LLC'),
  ('Doxazosin', 'Cardura Xl', 'US', 'Viatris Specialty LLC'),
  ('Doxepin', 'Prudoxin', 'US', 'Mylan Pharmaceuticals Inc.'),
  ('Doxepin', 'Silenor', 'US', 'Currax Pharmaceuticals LLC'),
  ('Doxepin', 'Zonalon', 'US', 'Mylan Pharmaceuticals Inc.'),
  ('Doxorubicin', 'Doxil', 'US', 'Baxter Healthcare Company'),
  ('Doxycycline', 'Doryx', 'GLOBAL', 'Mayne Pharma'),
  ('Doxycycline', 'Oracea', 'GLOBAL', 'Galderma'),
  ('Doxycycline', 'Vibramycin', 'GLOBAL', 'Pfizer'),
  ('Doxylamine', 'Nighttime Sleep Aid', 'US', 'Grocery Outlet'),
  ('Doxylamine', 'Sleep Aid', 'US', 'Meijer Distribution Inc'),
  ('Dronabinol', 'Marinol', 'US', 'ThePharmaNetwork, LLC'),
  ('Dronabinol', 'Syndros', 'US', 'Wellhouse Pharma, LLC'),
  ('Dulaglutide', 'Trulicity', 'US', 'Eli Lilly and Company'),
  ('Duloxetine', 'Cymbalta', 'US', 'Eli Lilly and Company'),
  ('Duloxetine', 'Drizalma Sprinkle', 'US', 'SUN PHARMACEUTICAL INDUSTRIES, INC.'),
  ('Dupilumab', 'Dupixent', 'US', 'Sanofi-Aventis U.S. LLC'),
  ('Durvalumab', 'Imfinzi', 'US', 'AstraZeneca Pharmaceuticals LP'),
  ('Ecallantide', 'Kalbitor', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Econazole', 'Ecoza', 'US', 'Resilia Pharmaceuticals, Inc.'),
  ('Eflapegrastim-Xnst', 'Rolvedon', 'US', 'Assertio Specialty Pharmaceuticals, LLC'),
  ('Elapegademase-Lvlr', 'Revcovi', 'US', 'Chiesi USA, Inc.'),
  ('Eltrombopag', 'Alvaiz', 'US', 'Teva Pharmaceuticals, Inc.'),
  ('Emapalumab-Lzsg', 'Gamifant', 'US', 'Swedish Orphan Biovitrum AB (publ)'),
  ('Emicizumab', 'Hemlibra', 'US', 'Genentech, Inc.'),
  ('Enalapril', 'Epaned', 'US', 'Azurity Pharmaceuticals, Inc.'),
  ('Enalapril', 'Vasotec', 'US', 'Bausch Health US LLC'),
  ('Enoxaparin', 'Lovenox', 'US', 'Sanofi-Aventis U.S. LLC'),
  ('Entecavir', 'Baraclude', 'US', 'E.R. Squibb & Sons, L.L.C.'),
  ('Epinephrine', 'Adrenalin', 'US', 'Par Health USA, LLC'),
  ('Epinephrine', 'Auvi-Q', 'US', 'Medical Purchasing Solutions, LLC'),
  ('Epinephrine', 'Neffy', 'US', 'Sportpharm LLC'),
  ('Eplerenone', 'Inspra', 'US', 'Viatris Specialty LLC'),
  ('Eravacycline', 'Xerava', 'US', 'Tetraphase Pharmaceuticals, Inc.'),
  ('Erenumab-Aooe', 'Aimovig', 'US', 'Amgen, Inc'),
  ('Eribulin', 'Halaven', 'US', 'Eisai Inc.'),
  ('Ertapenem', 'Invanz', 'US', 'Merck Sharp & Dohme LLC'),
  ('Erythromycin', 'Ery-Tab', 'US', 'Arbor Pharmaceuticals, Inc.'),
  ('Erythromycin Ethylsuccinate', 'E.E.S', 'US', 'Azurity Pharmaceuticals, Inc. (formerly Arbor Pharmaceuticals)'),
  ('Erythromycin Ethylsuccinate', 'E.E.S 400', 'US', 'Azurity Pharmaceuticals, Inc. (formerly Arbor Pharmaceuticals)'),
  ('Erythromycin Ethylsuccinate', 'Ery-Ped', 'US', 'Azurity Pharmaceuticals, Inc. (formerly Arbor Pharmaceuticals)'),
  ('Erythromycin Lactobionate', 'Erythrocin Lactobionate', 'US', 'Hospira, Inc.'),
  ('Escitalopram', 'Lexapro', 'US', 'Allergan, Inc.'),
  ('Esketamine', 'Spravato', 'US', 'Janssen Pharmaceuticals, Inc.'),
  ('Eslicarbazepine', 'Aptiom', 'US', 'Sumitomo Pharma America, Inc.'),
  ('Esmolol', 'Brevibloc', 'US', 'Baxter Healthcare Company'),
  ('Esomeprazole', 'Foster And Thrive Acid Reducer', 'US', 'Strategic Sourcing Services LLC'),
  ('Esomeprazole', 'Nexium', 'US', 'AstraZeneca Pharmaceuticals LP'),
  ('Esomeprazole', 'Nexium 24Hr', 'US', 'Haleon US Holdings LLC'),
  ('Estradiol', 'Climara', 'US', 'Bayer HealthCare Pharmaceuticals Inc.'),
  ('Estradiol', 'Divigel', 'US', 'Vertical Pharmaceuticals, LLC'),
  ('Estradiol', 'Dotti', 'US', 'Bryant Ranch Prepack'),
  ('Eszopiclone', 'Lunesta', 'US', 'Waylis Therapeutics LLC'),
  ('Etanercept', 'Enbrel', 'US', 'Immunex Corporation'),
  ('Etelcalcetide', 'Parsabiv', 'US', 'Amgen, Inc'),
  ('Eteplirsen', 'Exondys 51', 'US', 'Sarepta Therapeutics, Inc.'),
  ('Etomidate', 'Amidate', 'US', 'Henry Schein, Inc.'),
  ('Etomidate', 'Amidate', 'US', 'Henry Schein, Inc.'),
  ('Etoposide', 'Avopef', 'US', 'Avyxa Pharma, LLC'),
  ('Etoposide', 'Etopophos', 'US', 'H2-Pharma, LLC'),
  ('Etoposide', 'Vepesid', 'US', 'Amneal Pharmaceuticals NY LLC'),
  ('Etripamil', 'Cardamyst', 'US', 'Milestone Pharmaceuticals USA, Inc.'),
  ('Everolimus', 'Afinitor', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Everolimus', 'Torpenz', 'US', 'Upsher-Smith Laboratories, LLC'),
  ('Everolimus', 'Yulithira', 'US', 'CivicaScript, LLC'),
  ('Evolocumab', 'Repatha', 'US', 'Amgen USA Inc.'),
  ('Exenatide', 'Byetta', 'US', 'AstraZeneca Pharmaceuticals LP'),
  ('Ezetimibe', 'Zetia', 'US', 'Organon LLC'),
  ('Famotidine', 'Acid Controller', 'US', 'CVS Pharmacy'),
  ('Famotidine', 'Acid Reducer', 'US', 'CVS WOONSOCKET PRESCRIPTION CENTER, INCORPORATED'),
  ('Famotidine', 'Zantac 360', 'US', 'Navajo Manufacturing Company Inc.'),
  ('Febuxostat', 'Uloric', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Felbamate', 'Felbatol', 'US', 'Viatris Specialty LLC'),
  ('Felodipine', 'Felopdipine', 'US', 'A-S Medication Solutions'),
  ('Fenofibrate', 'Antara', 'US', 'Lupin Pharmaceuticals, Inc.'),
  ('Fenofibrate', 'Lipofen', 'US', 'ANI Pharmaceuticals, Inc.'),
  ('Fenofibrate', 'Tricor', 'US', 'A-S Medication Solutions'),
  ('Ferrous Sulfate', 'Ferrum Sulphuricum', 'US', 'Boiron'),
  ('Fexofenadine', 'Allegra', 'GLOBAL', 'Sanofi'),
  ('Fexofenadine', 'Fexet', 'GLOBAL', 'Getz Pharma'),
  ('Fexofenadine', 'Telfast', 'GLOBAL', 'Sanofi'),
  ('Fibrinogen Human', 'Fibryga', 'US', 'Octapharma USA Inc'),
  ('Fibrinogen Human', 'Riastap', 'US', 'CSL Behring GmbH'),
  ('Filgrastim', 'Neupogen', 'US', 'Amgen, Inc'),
  ('Filgrastim', 'Releuko', 'US', 'Amneal Pharmaceuticals LLC'),
  ('Filgrastim-Aafi', 'Nivestym', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Filgrastim-Laha', 'Filkri', 'US', 'Accord BioPharma Inc.,'),
  ('Filgrastim-Sndz', 'Zarxio', 'US', 'Sandoz Inc.'),
  ('Filgrastim-Txid', 'Nypozi', 'US', 'Cipla USA Inc.'),
  ('Filgrastim-Txid', 'Nypozi Txid', 'US', 'Tanvex BioPharma USA, Inc.'),
  ('Finasteride', 'Propecia', 'US', 'Organon LLC'),
  ('Finasteride', 'Proscar', 'US', 'Organon LLC'),
  ('Fitusiran', 'Qfitlia', 'US', 'Genzyme Corporation'),
  ('Fluconazole', 'Diflucan', 'US', 'Roerig'),
  ('Flucytosine', 'Ancobon', 'US', 'Bausch Health US LLC'),
  ('Fluocinolone Acetonide', 'Derma-Smoothe/Fs', 'US', 'Royal Pharmaceuticals'),
  ('Fluocinolone Acetonide', 'Dermotic', 'US', 'Royal Pharmaceuticals'),
  ('Fluocinolone Acetonide', 'Synalar', 'US', 'Medimetriks Pharmaceuticals, Inc.'),
  ('Fluocinonide', 'Vanos', 'US', 'Bausch Health US, LLC'),
  ('Fluorometholone', 'Flarex', 'US', 'Harrow Eye, LLC'),
  ('Fluorometholone', 'Fml', 'US', 'Allergan, Inc.'),
  ('Fluorometholone', 'Fml Forte', 'US', 'Allergan, Inc.'),
  ('Fluorouracil', 'Efudex', 'US', 'Bausch Health US, LLC'),
  ('Fluorouracil', 'Favlyxa', 'US', 'Avyxa Pharma, LLC'),
  ('Fluorouracil', 'Tolak', 'US', 'HILL DERMACEUTICALS, INC.'),
  ('Fluoxetine', 'Prozac', 'US', 'Dista Products Company'),
  ('Flurandrenolide', 'Cordran', 'US', 'INA Pharmaceutics, Inc'),
  ('Flurbiprofen', 'Lurbiro', 'US', 'IPG Pharmaceuticals, Inc.'),
  ('Fluticasone', 'Arnuity Ellipta', 'US', 'GlaxoSmithKline LLC'),
  ('Fluticasone', 'Flonase Sensimist Allergy Relief', 'US', 'Haleon US Holdings LLC'),
  ('Fluticasone', 'Good Sense 24 Hour Allergy Nasal', 'US', 'L. Perrigo Company'),
  ('Formoterol', 'Perforomist', 'US', 'Viatris Specialty LLC'),
  ('Fosinopril', 'Monopril', 'US', NULL),
  ('Fosphenytoin', 'Cerebyx', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Fremanezumab-Vfrm', 'Ajovy', 'US', 'Teva Pharmaceuticals USA, Inc.'),
  ('Fulvestrant', 'Cligavyx', 'US', 'Avyxa Pharma, LLC'),
  ('Fulvestrant', 'Faslodex', 'US', 'AstraZeneca Pharmaceuticals LP'),
  ('Furosemide', 'Furoscix', 'US', 'scPharmaceuticals Inc., a wholly owned subsidiary of MannKind Corporation'),
  ('Furosemide', 'Lasix', 'US', 'Validus Pharmaceuticals LLC'),
  ('Furosemide', 'Lasix Onyu', 'US', 'SQ Innovation, Inc.'),
  ('Gabapentin', 'Gralise', 'US', 'Almatica Pharma LLC'),
  ('Gabapentin', 'Neurontin', 'US', 'Viatris Specialty LLC'),
  ('Gabapentin', 'Relgaabi', 'US', 'Method Pharmaceuticals, LLC'),
  ('Galcanezumab-Gnlm', 'Emgality', 'US', 'Eli Lilly and Company'),
  ('Ganciclovir', 'Zirgan', 'US', 'Bausch & Lomb Incorporated'),
  ('Garadacimab', 'Andembry', 'US', 'CSL'),
  ('Gatifloxacin', 'Zymaxid', 'US', 'Allergan, Inc.'),
  ('Gemcitabine', 'Avgemsi', 'US', 'Avyxa Pharma, LLC'),
  ('Gemfibrozil', 'Lopid', 'US', 'Parke-Davis Div of Pfizer Inc'),
  ('Gentamicin', 'Gentak', 'US', 'Proficient Rx LP'),
  ('Glatiramer', 'Copaxone', 'US', 'Teva Neuroscience, Inc.'),
  ('Glatiramer', 'Glatopa', 'US', 'Bryant Ranch Prepack'),
  ('Glimepiride', 'Amaryl', 'GLOBAL', 'Sanofi'),
  ('Glimepiride', 'Getryl', 'GLOBAL', 'Getz Pharma'),
  ('Glimepiride', 'Glimy', 'GLOBAL', 'Dr Reddys'),
  ('Glipizide', 'Glucotrol Xl', 'US', 'Roerig'),
  ('Glucagon', 'Baqsimi', 'US', 'Amphastar Pharmaceuticals, Inc.'),
  ('Glucagon', 'Gvoke Hypopen 0.5 Mg Auto-Injector', 'US', 'Xeris Pharmaceuticals, Inc.'),
  ('Glucagon', 'Gvoke Hypopen 1 Mg Auto-Injector', 'US', 'Xeris Pharmaceuticals, Inc.'),
  ('Glycerin Ophthalmic', 'Regener-Eyes Ophthalmic Solution Lite', 'US', 'M & M PRODUCTS, LLC'),
  ('Glycerin Ophthalmic', 'Regener-Eyes Ophthalmic Solution Lite Xl', 'US', 'M & M PRODUCTS, L.L.C.'),
  ('Glycerin Ophthalmic', 'Silktears', 'US', 'SilkTears'),
  ('Glycopyrrolate', 'Cuvposa', 'US', 'Merz Pharmaceuticals, LLC'),
  ('Glycopyrrolate', 'Glycate', 'US', 'Intra-Sana Laboratories'),
  ('Glycopyrrolate', 'Glyrx-Pf', 'US', 'Exela Pharma Sciences, LLC'),
  ('Golimumab', 'Simponi', 'US', 'Janssen Biotech, Inc.'),
  ('Golimumab', 'Simponi Aria', 'US', 'Janssen Biotech, Inc.'),
  ('Goserelin', 'Zoladex', 'US', 'TerSera Therapeutics LLC'),
  ('Granisetron', 'Granisol', 'US', 'Intra-Sana Laboratories'),
  ('Granisetron', 'Sancuso', 'US', 'Cumberland Pharmaceuticals Inc.'),
  ('Granisetron', 'Sustol', 'US', 'Heron Therapeutics, Inc.'),
  ('Guaifenesin', 'Mucinex', 'US', 'A-S Medication Solutions'),
  ('Guaifenesin', 'Mucus Relief', 'US', 'Strategic Sourcing Services LLC'),
  ('Guanfacine', 'Intuniv', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Guselkumab', 'Tremfya', 'US', 'Janssen Biotech, Inc.'),
  ('Halobetasol', 'Bryhali', 'US', 'Bausch Health US, LLC'),
  ('Halobetasol', 'Lexette', 'US', 'Mayne Pharma'),
  ('Halobetasol', 'Ultravate', 'US', 'Lacer Pharma, LLC'),
  ('Haloperidol', 'Haldol Decanoate', 'US', 'Janssen Pharmaceuticals, Inc.'),
  ('Histamine Dihydrochloride', '2Nd Chance Mobility Pain Relief', 'US', 'ALPHA NUTRITION, LLC'),
  ('Histamine Dihydrochloride', 'Histaminum Hydrochloricum', 'US', 'Boiron'),
  ('Hyaluronidase', 'Amphadase', 'US', 'Amphastar Pharmaceuticals, Inc.'),
  ('Hydrochlorothiazide', 'HydroDIURIL', 'US', NULL),
  ('Hydrochlorothiazide', 'Microzide', 'US', NULL),
  ('Hydrocortisone', 'Alkindi Sprinkle', 'US', 'Eton Pharmaceuticals, Inc.'),
  ('Hydrocortisone', 'Anti Itch', 'US', 'Meijer, Inc.'),
  ('Hydrocortisone', 'Solu-Cortef', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Hydrocortisone Butyrate', 'Evesse', 'US', 'Perfero Pharma, Inc.'),
  ('Hydromorphone', 'Dilaudid', 'US', 'Rhodes Pharmaceuticals LLC'),
  ('Hydroquinone', 'Obagi C Rx System C Clarifying Serum', 'US', 'Obagi Cosmeceuticals LLC'),
  ('Hydroquinone', 'Olivia Quido Blemish Eraser', 'US', 'O Skin Care LLC'),
  ('Hydroxocobalamin', 'Cyanokit', 'US', 'BTG INTERNATIONAL INC.'),
  ('Ibandronate', 'Boniva', 'US', NULL),
  ('Ibuprofen', 'Advil', 'GLOBAL', 'Haleon'),
  ('Ibuprofen', 'Brufen', 'GLOBAL', 'Abbott'),
  ('Ibuprofen', 'Nurofen', 'GLOBAL', 'Reckitt'),
  ('Ibuprofen Lysine', 'Neoprofen', 'US', 'Recordati Rare Diseases Inc.'),
  ('Ibutilide', 'Corvert', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Icatibant', 'Firazyr', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Icatibant', 'Sajazir', 'US', 'Cycle Pharmaceuticals Ltd-Uk'),
  ('Ifosfamide', 'Ifex', 'US', 'Baxter Healthcare Corporation'),
  ('Iloperidone', 'Fanapt', 'US', 'Vanda Pharmaceuticals Inc.'),
  ('Imatinib', 'Gleevec', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Imatinib', 'Imkeldi', 'US', 'Shorla Oncology Inc.,'),
  ('Imetelstat', 'Rytelo', 'US', 'Geron Corporation'),
  ('Imiquimod', 'Zyclara', 'US', 'Bausch Health US, LLC'),
  ('Indomethacin', 'Indocin', 'US', 'Zyla Life Sciences US Inc.'),
  ('Infliximab', 'Remicade', 'US', 'Janssen Biotech, Inc.'),
  ('Insulin Glargine', 'Lantus', 'US', 'sanofi-aventis U.S. LLC'),
  ('Insulin Glargine', 'Lantus Solostar', 'US', 'sanofi-aventis U.S. LLC'),
  ('Insulin Glargine', 'Toujeo', 'US', 'A-S Medication Solutions'),
  ('Insulin Human', 'Afrezza', 'US', 'Mannkind Corporation'),
  ('Insulin Human', 'Humulin N', 'US', 'Eli Lilly and Company'),
  ('Insulin Human', 'Humulin R', 'US', 'Eli Lilly and Company'),
  ('Interferon Beta-1A', 'Avonex', 'US', 'Biogen Inc.'),
  ('Interferon Beta-1A', 'Rebif', 'US', 'EMD Serono, Inc.'),
  ('Interferon Beta-1A', 'Rebif Rebidose', 'US', 'EMD Serono, Inc.'),
  ('Interferon Gamma-1B', 'Actimmune', 'US', 'Horizon Therapeutics USA, Inc.'),
  ('Interferon Gamma-1B', 'Guna-Inf Gamma', 'US', 'Guna spa'),
  ('Ipratropium', 'Atrovent', 'GLOBAL', 'Boehringer Ingelheim'),
  ('Ipratropium', 'Ipravent', 'GLOBAL', 'Cipla'),
  ('Ipratropium', 'Rinatec', 'GLOBAL', 'Boehringer Ingelheim'),
  ('Irbesartan', 'Avapro', 'US', 'Sanofi-Aventis U.S. LLC'),
  ('Irinotecan', 'Camptosar', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Irinotecan', 'Onivyde', 'US', 'Ipsen Biopharmaceuticals, Inc.'),
  ('Isoflurane', 'Forane', 'US', 'Baxter Healthcare Corporation'),
  ('Isoflurane', 'Terrell', 'US', 'Piramal Critical Care, Inc.'),
  ('Isotretinoin', 'Absorica', 'US', 'Sun Pharmaceutical Industries, Inc.'),
  ('Isotretinoin', 'Accutane', 'US', 'JG Pharma Inc.'),
  ('Isotretinoin', 'Zenatane', 'US', 'Dr. Reddy''s Laboratories Limited'),
  ('Isradipine', 'DynaCirc', 'US', NULL),
  ('Ivermectin', 'Rid One And Done', 'US', 'Oystershell Consumer Health, Inc.'),
  ('Ivermectin', 'Soolantra', 'US', 'Galderma Laboratories, L.P.'),
  ('Ivermectin', 'Stromectol', 'US', 'Merck Sharp & Dohme LLC'),
  ('Ixekizumab', 'Taltz', 'US', 'Eli Lilly and Company'),
  ('Kali Muriaticum', 'Bm Kali Mur', 'US', 'BM Private Limited'),
  ('Kali Sulphuricum', 'Bestmade Natural Products Kali Sulph', 'US', 'Bestmade Natural Products'),
  ('Kali Sulphuricum', 'Bestmade Natural Products Kali Sulph 8X', 'US', 'Bestmade Natural Products'),
  ('Kali Sulphuricum', 'Bm Kali Sulph', 'US', 'BM Private Limited'),
  ('Ketamine', 'Ketalar', 'US', 'Par Health USA, LLC'),
  ('Ketoconazole', 'Anti Dandruff', 'US', 'Guangzhou ChuanMa International Trading Co.,Ltd.'),
  ('Ketoconazole', 'Ketodan', 'US', 'Medimetriks Pharmaceuticals, Inc.'),
  ('Ketoconazole', 'Nizoral', 'US', 'Kramer Laboratories'),
  ('Ketorolac', 'Acular Ls', 'US', 'Allergan, Inc.'),
  ('Ketorolac', 'Toronova Ii Suik', 'US', 'Asclemed USA, Inc.'),
  ('Ketorolac', 'Toronova Suik', 'US', 'Advanced Rx of Tennessee, LLC'),
  ('Ketotifen', 'Alaway', 'US', 'Bausch & Lomb Incorporated'),
  ('Ketotifen', 'Equate Eye Itch Relief', 'US', 'Wal-Mart Stores, Inc.'),
  ('Ketotifen', 'Eye Itch Relief', 'US', 'CVS Pharmacy'),
  ('Labetalol', 'Trandate', 'US', NULL),
  ('Lacosamide', 'Motpoly Xr', 'US', 'Aucta Pharmaceuticals, Inc.'),
  ('Lacosamide', 'Vimpat', 'US', 'UCB, Inc.'),
  ('Lactulose', 'Constulose', 'US', 'Actavis Pharma, Inc.'),
  ('Lactulose', 'Enulose', 'US', 'Bryant Ranch Prepack'),
  ('Lactulose', 'Kristalose', 'US', 'Cumberland Pharmaceuticals Inc.'),
  ('Lamotrigine', 'Lamictal', 'US', 'GlaxoSmithKline LLC'),
  ('Lamotrigine', 'Lamictal Xr', 'US', 'GlaxoSmithKline LLC'),
  ('Lamotrigine', 'Subvenite', 'US', 'OWP Pharmaceuticals, Inc.'),
  ('Lanadelumab-Flyo', 'Takhzyro', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Lansoprazole', 'Prevacid', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Lansoprazole', 'Prevacid 24 Hr', 'US', 'L. Perrigo Company'),
  ('Lansoprazole', 'Prevacid Solutab', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Latanoprost', 'Xalatan', 'US', 'Viatris Specialty LLC'),
  ('Latanoprost', 'Xelpros', 'US', 'Sun Pharmaceutical Industries, Inc.'),
  ('Latanoprostene Bunod', 'Vyzulta', 'US', 'Bausch & Lomb Incorporated'),
  ('Lebrikizumab-Lbkz', 'Ebglyss', 'US', 'Eli Lilly and Company'),
  ('Leflunomide', 'Arava', 'US', 'sanofi-aventis U.S. LLC'),
  ('Lenalidomide', 'Revlimid', 'US', 'Celgene Corporation'),
  ('Letermovir', 'Prevymis', 'US', 'Merck Sharp & Dohme LLC'),
  ('Leucovorin', 'Vykoura', 'US', 'Avyxa Pharma, LLC'),
  ('Leuprolide', 'Camcevi', 'US', 'Accord BioPharma, Inc.'),
  ('Leuprolide', 'Eligard', 'US', 'TOLMAR Inc.'),
  ('Leuprolide', 'Vabrinty', 'US', 'URONOVA PHARMACEUTICALS, INC.'),
  ('Levalbuterol', 'Xopenex Hfa', 'US', 'Lupin Pharmaceuticals, Inc.'),
  ('Levetiracetam', 'Keppra', 'US', 'UCB, Inc.'),
  ('Levetiracetam', 'Keppra', 'US', 'UCB, Inc.'),
  ('Levetiracetam', 'Keppra Xr', 'US', 'UCB, Inc.'),
  ('Levetiracetam', 'Keppra Xr', 'US', 'UCB, Inc.'),
  ('Levetiracetam', 'Spritam', 'US', 'Aprecia Pharmaceuticals, LLC'),
  ('Levetiracetam', 'Spritam', 'US', 'Aprecia Pharmaceuticals, LLC'),
  ('Levocetirizine Dihydrochloride', 'Allergy Relief', 'US', 'Albertsons Companies'),
  ('Levocetirizine Dihydrochloride', 'Childrens Xyzal Allergy', 'US', 'Chattem, Inc.'),
  ('Levocetirizine Dihydrochloride', 'Xyzal Allergy 24Hr', 'US', 'Chattem, Inc.'),
  ('Levonorgestrel', 'Julie', 'US', 'Julie Products Inc.'),
  ('Levonorgestrel', 'My Way', 'US', 'Proficient Rx LP'),
  ('Levonorgestrel', 'Postday One-Step', 'US', 'Rapha Pharmaceuticals, Inc.'),
  ('Levothyroxine', 'Synthroid', 'US', 'AbbVie Inc.'),
  ('Levothyroxine', 'Tirosint', 'US', 'IBSA Pharma Inc.'),
  ('Levothyroxine', 'Tirosint Sol', 'US', 'IBSA Pharma Inc.'),
  ('Lidocaine', 'Pain Relief Patches', 'US', 'Walgreen Company'),
  ('Lidocaine', 'Xylocaine', 'US', 'Henry Schein, Inc.'),
  ('Lidocaine', 'Xylocaine Mpf', 'US', 'Fresenius Kabi USA, LLC'),
  ('Lidocaine Hci', 'Burn Gel', 'US', 'Trifecta Pharmaceuticals USA LLC'),
  ('Lidocaine Hci', 'Electrum Numb Foam', 'US', 'RENU LABORATORIES, LLC'),
  ('Lidocaine Hci', 'First Shield', 'US', 'Ever Ready First Aid'),
  ('Lidocaine Hcl', 'Aloe Vera Gel', 'US', 'Valu Merchandisers Company'),
  ('Lidocaine Hcl', 'Lidoguard', 'US', 'ViolaCare, Inc.'),
  ('Lidocaine Hcl', 'Sunburn Relief Gel', 'US', 'Jell Pharmaceuticals Pvt. Ltd'),
  ('Lidocaine Hydrochloride Otic', 'Earbalance Ear Pain Drops', 'US', 'Marie''s Original Formulas LLC'),
  ('Lifitegrast', 'Xiidra', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Linagliptin', 'Tradjenta', 'US', 'A-S Medication Solutions'),
  ('Lincomycin', 'Lincocin', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Linezolid', 'Zyvox', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Liothyronine', 'Cytomel', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Liothyronine', 'Liomny', 'US', 'SIGMAPHARM LABORATORIES, LLC'),
  ('Liraglutide', 'Saxenda', 'US', 'A-S Medication Solutions'),
  ('Liraglutide', 'Victoza', 'US', 'A-S Medication Solutions'),
  ('Lisdexamfetamine Dimesylate', 'Arynta', 'US', 'Azurity Pharmaceuticals, Inc.'),
  ('Lisdexamfetamine Dimesylate', 'Vyvanse', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Lisinopril', 'Qbrelis', 'US', 'Azurity Pharmaceuticals, Inc.'),
  ('Lisinopril', 'Zestril', 'US', 'Upsher-Smith Laboratories, LLC'),
  ('Loperamide', 'Anti Diarrheal', 'US', 'CVS Pharmacy'),
  ('Loperamide', 'Anti-Diarrheal', 'US', 'Rite Aid Corporation'),
  ('Loperamide', 'Good Sense Anti Diarrheal', 'US', 'Proficient Rx LP'),
  ('Loratadine', 'Claritin', 'GLOBAL', 'Bayer'),
  ('Loratadine', 'Lorano', 'GLOBAL', 'Hexal'),
  ('Loratadine', 'Softin', 'GLOBAL', 'Highnoon Laboratories'),
  ('Lorazepam', 'Ativan', 'US', 'Hikma Pharmaceuticals USA Inc.'),
  ('Lorazepam', 'Loreev Xr', 'US', 'Almatica Pharma LLC'),
  ('Losartan', 'Cozaar', 'GLOBAL', 'Organon'),
  ('Losartan', 'Losacar', 'GLOBAL', 'Zydus'),
  ('Losartan', 'Repace', 'GLOBAL', 'Sami Pharmaceuticals'),
  ('Loteprednol Etabonate', 'Alrex', 'US', 'Bausch & Lomb Incorporated'),
  ('Loteprednol Etabonate', 'Inveltys', 'US', 'Alcon Laboratories, Inc.'),
  ('Loteprednol Etabonate', 'Lotemax', 'US', 'Bausch & Lomb Incorporated'),
  ('Lotilaner Ophthalmic', 'Xdemvy', 'US', 'Tarsus Pharmaceuticals, Inc.'),
  ('Lubiprostone', 'Amitiza', 'US', 'SpecGx LLC'),
  ('Lubiprostone', 'Amitza', 'US', 'Direct_Rx'),
  ('Lurasidone', 'Latuda', 'US', 'Sumitomo Pharma America, Inc.'),
  ('Luspatercept', 'Reblozyl', 'US', 'Celgene Corporation'),
  ('Magnesium Hydroxide', 'Mag-Ox', 'GLOBAL', 'Blaine Pharmaceuticals'),
  ('Magnesium Hydroxide', 'Milk of Magnesia', 'GLOBAL', 'Bayer'),
  ('Magnesium Hydroxide', 'Milpar', 'GLOBAL', 'Sanofi'),
  ('Magnesium Sulfate Heptahydrate', 'Magnesium Sulfate In 5% Dextrose', 'US', 'Fresenius Kabi USA, LLC'),
  ('Magnesium Sulfate Heptahydrate', 'Magnesium Sulfate In Water', 'US', 'B. Braun Medical Inc.'),
  ('Magnesium Sulfate Heptahydrate', 'Nuvalu Epsom Salt', 'US', 'J C SALES'),
  ('Maraviroc', 'Selzentry', 'US', 'ViiV Healthcare Company'),
  ('Margetuximab-Cmkb', 'Margenza', 'US', 'TerSera Therapeutics LLC'),
  ('Marstacimab-Hncq', 'Hympavzi', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Meclizine', 'Dramamine', 'US', 'Medtech Products Inc.'),
  ('Meclizine', 'Motion Sickness', 'US', 'Strategic Sourcing Services LLC'),
  ('Meclizine', 'Motion Sickness Relief', 'US', 'TARGET CORPORATION'),
  ('Medroxyprogesterone', 'Depo-Provera', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Medroxyprogesterone', 'Depo-Subq Provera', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Medroxyprogesterone', 'Provera', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Mefenamic Acid', 'Mefnac', 'GLOBAL', 'Sami Pharmaceuticals'),
  ('Mefenamic Acid', 'Ponstan', 'GLOBAL', 'Pfizer'),
  ('Mefenamic Acid', 'Ponstel', 'GLOBAL', 'Atnahs Pharma'),
  ('Meloxicam', 'Qamzova', 'US', 'Nanjing Delova Biotech Co., Ltd.'),
  ('Meloxicam', 'Xifyrm', 'US', 'Azurity Pharmaceuticals, Inc.'),
  ('Meloxicam', 'Zybic', 'US', 'Redmont Pharmaceuticals, LLC'),
  ('Melphalan', 'Evomela', 'US', 'Acrotech Biopharma Inc'),
  ('Melphalan', 'Ivra', 'US', 'Apotex Corp'),
  ('Meperidine', 'Demerol', 'US', 'Hospira, Inc.'),
  ('Mepivacaine', 'Carbocaine', 'US', 'Septodont, Inc.'),
  ('Mepivacaine', 'Polocaine', 'US', 'Fresenius Kabi USA, LLC'),
  ('Mepivacaine', 'Polocaine-Mpf', 'US', 'Fresenius Kabi USA, LLC'),
  ('Mepolizumab', 'Nucala', 'US', 'GlaxoSmithKline LLC'),
  ('Mesalamine', 'Apriso', 'US', 'Salix Pharmaceuticals, Inc.'),
  ('Mesalamine', 'Canasa', 'US', 'Allergan, Inc.'),
  ('Mesalamine', 'Pentasa', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Mesna', 'Mesnex', 'US', 'Baxter Healthcare Company'),
  ('Metformin', 'Fortamet', 'GLOBAL', 'Shionogi'),
  ('Metformin', 'Glucophage', 'GLOBAL', 'Merck'),
  ('Metformin', 'Glumet', 'GLOBAL', 'Getz Pharma'),
  ('Methadone', 'Diskets', 'US', 'Hikma Pharmaceuticals USA Inc.'),
  ('Methadone', 'Methadose', 'US', 'SpecGx LLC'),
  ('Methadone', 'Methadose Dispersible', 'US', 'SpecGx LLC'),
  ('Methocarbamol', 'Atmeksi', 'US', 'Rosemont Pharmaceuticals LLC'),
  ('Methocarbamol', 'Robaxin', 'US', 'Hikma Pharmaceuticals USA Inc.'),
  ('Methocarbamol', 'Tanlor', 'US', 'Forte Bio-Pharma'),
  ('Methohexital', 'Brevital Sodium', 'US', 'Par Health USA, LLC'),
  ('Methotrexate', 'Otrexup', 'US', 'Antares Pharma, Inc.'),
  ('Methotrexate', 'Rasuvo', 'US', 'Medexus Pharma Inc.'),
  ('Methotrexate', 'Trexall', 'US', 'Teva Women''s Health LLC'),
  ('Methoxy Polyethylene Glycol-Epoetin Beta', 'Mircera', 'US', 'Vifor (International) Inc.'),
  ('Methylcellulose', 'Citrucel', 'US', 'Haleon US Holdings LLC'),
  ('Methylcellulose', 'Drx Choice Fiber Therapy', 'US', 'RARITAN PHARMACEUTICALS INC'),
  ('Methylcellulose', 'Fiber Therapy', 'US', 'Preferred Pharmaceuticals Inc.'),
  ('Methyldopa', 'Aldomet', 'US', NULL),
  ('Methylene Blue', 'Provayblue', 'US', 'American Regent, Inc.'),
  ('Methylnaltrexone', 'Relistor', 'US', 'Salix Pharmaceuticals, Inc.'),
  ('Methylphenidate', 'Metadate Cd', 'US', 'Lannett Company, LLC'),
  ('Methylphenidate', 'Relexxii', 'US', 'Vertical Pharmaceuticals, LLC'),
  ('Methylphenidate', 'Ritalin', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Methylprednisolone', 'Depo-Medrol', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Methylprednisolone', 'Medrol', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Methylprednisolone', 'Solu-Medrol', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Metoclopramide', 'Gimoti', 'US', 'Evoke Pharma, Inc.'),
  ('Metoclopramide', 'Reglan', 'US', 'ANI Pharmaceuticals, Inc.'),
  ('Metolazone', 'Zaroxolyn', 'US', NULL),
  ('Metoprolol', 'Betaloc', 'GLOBAL', 'Recordati'),
  ('Metoprolol', 'Lopressor', 'GLOBAL', 'Novartis'),
  ('Metoprolol', 'Toprol-XL', 'GLOBAL', 'AstraZeneca'),
  ('Metronidazole', 'Flagyl', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Metronidazole', 'Likmez', 'US', 'Saptalis Pharmaceuticals, LLC'),
  ('Metronidazole', 'Noritate', 'US', 'Bausch Health US, LLC'),
  ('Micafungin', 'Mycamine', 'US', 'Astellas Pharma US, Inc.'),
  ('Miconazole', 'Anti-Fungal Powder', 'US', 'CVS Pharmacy'),
  ('Miconazole', 'Medline', 'US', 'Medline Industries, LP'),
  ('Miconazole', 'Natouch', 'US', 'Natouch LLC'),
  ('Midazolam', 'Nayzilam', 'US', 'UCB, Inc.'),
  ('Miglitol', 'Glyset', 'US', NULL),
  ('Minocycline', 'Amzeeq', 'US', 'Journey Medical Corporation'),
  ('Minocycline', 'Arestin', 'US', 'OraPharma, Inc.'),
  ('Minocycline', 'Minocin', 'US', 'Melinta Therapeutics, LLC'),
  ('Minoxidil', 'Basic Care Hair Regrowth Treatment', 'US', 'Amazon.com Services LLC'),
  ('Minoxidil', 'Equate Hair Regrowth Treatment', 'US', 'Wal-Mart Stores Inc'),
  ('Minoxidil', 'Hair Regrowth Treatment', 'US', 'Meijer, Inc.'),
  ('Mirikizumab-Mrkz', 'Omvoh', 'US', 'Eli Lilly and Company'),
  ('Mirtazapine', 'Remeron', 'US', 'Organon LLC'),
  ('Mirtazapine', 'Remeronsoltab', 'US', 'Organon LLC'),
  ('Misoprostol', 'Cytotec', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Mitomycin', 'Mutamycin', 'US', 'Accord BioPharma Inc.'),
  ('Modafinil', 'Provigil', 'US', 'Golden State Medical Supply, Inc.'),
  ('Mometasone', 'Allergy', 'US', 'CVS WOONSOCKET PRESCRIPTION CENTER, INCORPORATED'),
  ('Mometasone', 'Asmanex', 'US', 'Organon LLC'),
  ('Mometasone', 'Asmanex Hfa', 'US', 'Organon LLC'),
  ('Montelukast', 'Montair', 'GLOBAL', 'Cipla'),
  ('Montelukast', 'Montiget', 'GLOBAL', 'Getz Pharma'),
  ('Montelukast', 'Singulair', 'GLOBAL', 'Organon'),
  ('Morphine', 'Duramorph', 'US', 'Hikma Pharmaceuticals USA Inc.'),
  ('Morphine', 'Ms Contin', 'US', 'Rhodes Pharmaceuticals LLC'),
  ('Morphine', 'Opium Tincture Deodorized', 'US', 'Edenbridge Pharmaceuticals, LLC'),
  ('Motixafortide', 'Aphexda', 'US', 'Gamida Cell Inc.'),
  ('Moxifloxacin', 'Vigamox', 'US', 'Harrow Eye, LLC'),
  ('Mupirocin', 'Pirnuo', 'US', 'Glenmark Pharmaceuticals Inc., USA'),
  ('Mycophenolate Mofetil', 'Cellcept', 'US', 'Genentech, Inc.'),
  ('Mycophenolate Mofetil', 'Myhibbin', 'US', 'Azurity Pharmaceuticals, Inc.'),
  ('Mycophenolic Acid', 'Myfortic', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Nabumetone', 'Relafen Ds', 'US', 'Carwin Pharmaceutical Associates, LLC'),
  ('Nadolol', 'Corgard', 'US', NULL),
  ('Naftifine', 'Naftin', 'US', 'Legacy Pharma USA Inc.'),
  ('Nalmefene', 'Opvee', 'US', 'Indivior Inc.'),
  ('Nalmefene', 'Zurnai', 'US', 'Knoa Pharma LLC'),
  ('Naloxone', 'Kloxxado', 'US', 'Hikma Specialty USA Inc.'),
  ('Naloxone', 'Narcan', 'US', 'A-S Medication Solutions'),
  ('Naloxone', 'Rextovy', 'US', 'International Medication Systems, Ltd.'),
  ('Naproxen', 'Aleve', 'GLOBAL', 'Bayer'),
  ('Naproxen', 'Naprosyn', 'GLOBAL', 'Atnahs Pharma'),
  ('Naproxen', 'Synflex', 'GLOBAL', 'Roche'),
  ('Natamycin', 'Natacyn', 'US', 'Harrow Eye, LLC'),
  ('Nateglinide', 'Starlix', 'US', NULL),
  ('Nebivolol', 'Bystolic', 'US', 'Allergan, Inc.'),
  ('Nelarabine', 'Arranon', 'US', 'Sandoz Inc'),
  ('Neostigmine Methylsulfate', 'Bloxiverz', 'US', 'Exela Pharma Sciences, LLC'),
  ('Nepafenac', 'Ilevro', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Nepafenac', 'Nevanac', 'US', 'Harrow Eye, LLC'),
  ('Netarsudil', 'Rhopressa', 'US', 'Alcon Laboratories, Inc.'),
  ('Niacinamide', 'Dr.Jucre Rebirth', 'US', 'NATURECELL CO., LTD.'),
  ('Nicardipine', 'Cardene Iv', 'US', 'Baxter Healthcare Corporation'),
  ('Nicotine', 'Nicoderm Cq', 'US', 'Haleon US Holdings LLC'),
  ('Nicotine Polacrilex', 'Basic Care Nicotine', 'US', 'Amazon.com Services LLC'),
  ('Nicotine Polacrilex', 'Mini Nicotine', 'US', 'Meijer, Inc.'),
  ('Nicotine Polacrilex', 'Nicotine Mini', 'US', 'Rising Pharma Holdings, Inc.'),
  ('Nicotine Transdermal System', 'Habitrol Step 1', 'US', 'Dr. Reddy''s Laboratories Inc.'),
  ('Nicotine Transdermal System', 'Habitrol Step 2', 'US', 'Dr. Reddy''s Laboratories Inc.'),
  ('Nicotine Transdermal System', 'Habitrol Step 3', 'US', 'Dr. Reddy''s Laboratories Inc.'),
  ('Nifedipine', 'Procardia Xl', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Nilotinib', 'Cavhanza', 'US', 'Cycle Pharmaceuticals Ltd'),
  ('Nilotinib', 'Danziten', 'US', 'Azurity Pharmaceuticals, Inc.'),
  ('Nilotinib', 'Tasigna', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Nintedanib', 'Ofev', 'US', 'Boehringer Ingelheim Pharmaceuticals, Inc.'),
  ('Nirsevimab', 'Beyfortus', 'US', 'Sanofi Vaccines US Inc.'),
  ('Nisoldipine', 'Sular', 'US', 'Covis Pharma US, Inc'),
  ('Nitroglycerin', 'Glonoinum', 'US', 'Boiron'),
  ('Nitroglycerin', 'Nitro-Dur', 'US', 'Ingenus Pharmaceuticals, LLC'),
  ('Nitroglycerin', 'Nitrostat', 'US', 'Viatris Specialty LLC'),
  ('Nivolumab', 'Opdivo', 'US', 'E.R. Squibb & Sons, L.L.C.'),
  ('Nortriptyline', 'Pamelor', 'US', 'SpecGx LLC'),
  ('Nystatin', 'Klayesta', 'US', 'Epic Pharma, LLC'),
  ('Nystatin', 'Mycostatin', 'US', 'Direct_Rx'),
  ('Nystatin', 'Nystop', 'US', 'Bryant Ranch Prepack'),
  ('Nystatin Topical', 'Klayesta', 'US', 'Epic Pharma, LLC'),
  ('Ofloxacin', 'Ocuflox', 'US', 'Allergan, Inc.'),
  ('Olanzapine', 'Zyprexa', 'US', 'H2-Pharma LLC'),
  ('Olanzapine', 'Zyprexa Intramuscular', 'US', 'H2-Pharma LLC'),
  ('Olanzapine', 'Zyprexa Zydis', 'US', 'H2-Pharma LLC'),
  ('Oliceridine', 'Olinvyk', 'US', 'Trevena, Inc.'),
  ('Olipudase Alfa-Rpcp', 'Xenpozyme', 'US', 'Genzyme Corporation'),
  ('Olmesartan Medoxomil', 'Benicar', 'US', 'Cosette Pharmaceuticals, Inc.'),
  ('Olopatadine', 'Eye Allergy Itch And Redness Relief', 'US', 'CARDINAL HEALTH 110, LLC. DBA LEADER'),
  ('Olopatadine', 'Eye Allergy Itch Relief', 'US', 'CARDINAL HEALTH 110, LLC. DBA LEADER'),
  ('Olopatadine', 'Pataday Once Daily Relief', 'US', 'Alcon Laboratories, Inc.'),
  ('Omalizumab', 'Xolair', 'US', 'Genentech, Inc.'),
  ('Omalizumab', 'Xolair Pfs', 'US', 'Genentech, Inc.'),
  ('Omeprazole', 'Losec', 'GLOBAL', 'AstraZeneca'),
  ('Omeprazole', 'Prilosec', 'GLOBAL', 'AstraZeneca'),
  ('Omeprazole', 'Risek', 'GLOBAL', 'Getz Pharma'),
  ('Omidenepag Isopropyl', 'Omlonti', 'US', 'Ocuvex Therapeutics, Inc.'),
  ('ORS', 'Dioralyte', 'GLOBAL', 'Sanofi'),
  ('ORS', 'Pedialyte', 'GLOBAL', 'Abbott'),
  ('ORS', 'Peditral', 'GLOBAL', 'Sanofi'),
  ('Oseltamivir', 'Tamiflu', 'US', 'Genentech, Inc.'),
  ('Oxcarbazepine', 'Oxtellar Xr', 'US', 'Supernus Pharmaceuticals, Inc.'),
  ('Oxcarbazepine', 'Trileptal', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Oxycodone', 'Oxycontin', 'US', 'Knoa Pharma LLC'),
  ('Oxycodone', 'Roxybond', 'US', 'Protega Pharmaceuticals Inc'),
  ('Oxycodone', 'Xtampza Er', 'US', 'Collegium Pharmaceutical, Inc.'),
  ('Oxymetazoline', 'Major Nasal Decongestant', 'US', 'Major Pharmaceuticals'),
  ('Oxymetazoline', 'Nasal', 'US', 'Rite Aid Corporation'),
  ('Oxymetazoline', 'No Drip Nasal Mist', 'US', 'CVS Health'),
  ('Paclitaxel', 'Abraxane', 'US', 'Abraxis BioScience, LLC'),
  ('Paliperidone', 'Invega', 'US', 'Janssen Pharmaceuticals, Inc.'),
  ('Paliperidone Palmitate', 'Erzofri Extended-Release', 'US', 'Shandong Luye Pharmaceutical Co., Ltd.'),
  ('Paliperidone Palmitate', 'Invega Sustenna', 'US', 'Janssen Pharmaceuticals, Inc.'),
  ('Paliperidone Palmitate', 'Invega Trinza', 'US', 'Janssen Pharmaceuticals, Inc'),
  ('Palivizumab', 'Synagis', 'US', 'Swedish Orphan Biovitrum AB (publ)'),
  ('Palonosetron', 'Posfrea', 'US', 'Avyxa Pharma, LLC'),
  ('Pantoprazole', 'Controloc', 'GLOBAL', 'Takeda'),
  ('Pantoprazole', 'Protonix', 'GLOBAL', 'Pfizer'),
  ('Pantoprazole', 'Zoltan', 'GLOBAL', 'Getz Pharma'),
  ('Paracetamol', 'Calpol', 'GLOBAL', 'Haleon'),
  ('Paracetamol', 'Panadol', 'GLOBAL', 'Haleon'),
  ('Paracetamol', 'Tylenol', 'GLOBAL', 'Kenvue'),
  ('Paricalcitol', 'Zemplar', 'US', 'AbbVie Inc.'),
  ('Paroxetine', 'Brisdelle', 'US', 'Legacy Pharma USA, Inc.'),
  ('Paroxetine', 'Paxil', 'US', 'Apotex Corp'),
  ('Paroxetine', 'Paxil Cr', 'US', 'Apotex Corp'),
  ('Pectin', 'Lolleez Orange Mango', 'US', 'BFY LLC'),
  ('Pectin', 'Lolleez Variety Pack', 'US', 'BFY LLC'),
  ('Pectin', 'Lolleez Watermelon', 'US', 'BFY LLC'),
  ('Pegaspargase', 'Oncaspar', 'US', 'Servier Pharmaceuticals LLC'),
  ('Pegcetacoplan', 'Empaveli', 'US', 'Apellis Pharmaceuticals, Inc.'),
  ('Pegcetacoplan', 'Syfovre', 'US', 'Apellis Pharmaceuticals, Inc.'),
  ('Pegfilgrastim', 'Fylnetra', 'US', 'Amneal Pharmaceuticals LLC'),
  ('Pegfilgrastim', 'Neulasta', 'US', 'Amgen, Inc'),
  ('Pegfilgrastim-Cbqv', 'Udenyca', 'US', 'Coherus Oncology, Inc.'),
  ('Peginterferon Alfa-2A', 'Pegasys', 'US', 'pharmaand GmbH'),
  ('Peginterferon Beta-1A', 'Plegridy', 'US', 'Biogen Inc.'),
  ('Peginterferon Beta-1A', 'Plegridy Pen', 'US', 'Biogen Inc.'),
  ('Pegloticase', 'Krystexxa', 'US', 'Horizon Therapeutics USA, Inc.'),
  ('Pegunigalsidase Alfa', 'Elfabrio', 'US', 'Chiesi USA, Inc.'),
  ('Pegvaliase-Pqpz', 'Palynziq', 'US', 'BioMarin Pharmaceutical Inc.'),
  ('Pegzilarginase-Nbln', 'Loargys', 'US', 'Immedica Pharma US Inc.'),
  ('Pemetrexed', 'Alimta', 'US', 'Eli Lilly and Company'),
  ('Pemetrexed', 'Axtle', 'US', 'Avyxa Pharma, LLC'),
  ('Pemetrexed', 'Pemrydi Rtu', 'US', 'Amneal Pharmaceuticals LLC'),
  ('Penciclovir', 'Denavir', 'US', 'Mylan Pharmaceuticals Inc.'),
  ('Penicillin G', 'Pfizerpen', 'US', 'Roerig'),
  ('Penicillin G Benzathine', 'Bicillin L-A', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Perampanel', 'Fycompa', 'US', 'Eisai Inc.'),
  ('Perindopril', 'Aceon', 'US', NULL),
  ('Phenol', 'Carbolicum Acidum', 'US', 'Boiron'),
  ('Phenol', 'Sore Throat', 'US', 'EQUATE (Wal-Mart Stores, Inc.) (see also WAL-MART INC)'),
  ('Phenol', 'Sore Throat Cherry', 'US', 'QUALITY CHOICE (Chain Drug Marketing Association)'),
  ('Phentermine', 'Lomaira', 'US', 'KVK-TECH, INC.'),
  ('Phentolamine', 'Oraverse', 'US', 'Septodont, Inc.'),
  ('Phentolamine', 'Ryzumvi', 'US', 'Oyster Point Pharma, Inc.'),
  ('Phenytoin', 'Dilantin Infatabs', 'US', 'Parke-Davis Div of Pfizer Inc'),
  ('Phenytoin', 'Dilantin-125', 'US', 'Viatris Specialty LLC'),
  ('Phenytoin', 'Phenytek', 'US', 'Mylan Pharmaceuticals Inc.'),
  ('Phytonadione', 'Vitamin K1', 'US', 'Hospira, Inc.'),
  ('Pioglitazone', 'Actos', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Pirfenidone', 'Esbriet', 'US', 'Genentech, Inc.'),
  ('Pitavastatin', 'Livalo', 'US', 'Kowa Pharmaceuticals America, Inc.'),
  ('Pitavastatin', 'Zypitamag', 'US', 'Zydus Lifesciences Limited'),
  ('Plerixafor', 'Mozobil', 'US', 'Sanofi-Aventis U.S. LLC'),
  ('Polyethylene Glycol 3350', 'Clearlax', 'US', 'STRATEGIC SOURCING SERVICES LLC'),
  ('Polyethylene Glycol 3350', 'Gavilax', 'US', 'Lupin Pharmaceuticals,Inc.'),
  ('Polyethylene Glycol 3350', 'Miralax', 'US', 'Bayer HealthCare LLC.'),
  ('Pomalidomide', 'Pomalyst', 'US', 'Celgene Corporation'),
  ('Posaconazole', 'Noxafil', 'US', 'Merck Sharp & Dohme LLC'),
  ('Potassium Iodide', 'Iosat', 'US', 'Anbex Inc.'),
  ('Potassium Iodide', 'Kali Iodatum', 'US', 'Boiron'),
  ('Potassium Iodide', 'Sski', 'US', 'ATLANTIC BIOLOGICALS CORP.'),
  ('Pozelimab', 'Veopoz', 'US', 'Regeneron Pharmaceuticals, Inc.'),
  ('Pralatrexate', 'Folotyn', 'US', 'Acrotech Biopharma Inc'),
  ('Pralidoxime', 'Protopam Chloride', 'US', 'Baxter Healthcare Corporation'),
  ('Pramlintide', 'Symlinpen', 'US', 'AstraZeneca Pharmaceuticals LP'),
  ('Prasugrel', 'Effient', 'US', 'Cosette Pharmaceuticals, Inc.'),
  ('Prednisolone', 'Orapred Odt', 'US', 'Advanz Pharma (US) Corp.'),
  ('Prednisolone', 'Pred Forte', 'US', 'Allergan, Inc.'),
  ('Prednisolone', 'Pred Mild', 'US', 'Allergan, Inc.'),
  ('Pregabalin', 'Lyrica', 'US', 'Viatris Specialty LLC'),
  ('Pregabalin', 'Lyrica Cr', 'US', 'Viatris Specialty LLC'),
  ('Prochlorperazine', 'Compro', 'US', 'PD-Rx Pharmaceuticals, Inc.'),
  ('Progesterone', 'Bunuss Phyto-Pro Skin Cream', 'US', 'Jiashen International Trade Limited'),
  ('Progesterone', 'Crinone', 'US', 'Allergan, Inc.'),
  ('Progesterone', 'Prometrium', 'US', 'Acertis Pharmaceuticals, LLC'),
  ('Promethazine', 'Phenergan', 'US', 'Hikma Pharmaceuticals USA Inc.'),
  ('Promethazine', 'Promethegan', 'US', 'Cosette Pharmaceuticals, Inc.'),
  ('Proparacaine', 'Alcaine', 'US', 'Alcon Laboratories, Inc.'),
  ('Propofol', 'Diprivan', 'US', 'Fresenius Kabi USA, LLC'),
  ('Propranolol', 'Hemangeol', 'US', 'Eton Pharmaceuticals, Inc.'),
  ('Propranolol', 'Inderal La', 'US', 'ANI Pharmaceuticals, Inc.'),
  ('Propranolol', 'Inderal Xl', 'US', 'ANI Pharmaceuticals, Inc.'),
  ('Prucalopride', 'Motegrity', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Quetiapine', 'Seroquel', 'US', 'AstraZeneca Pharmaceuticals LP'),
  ('Quetiapine', 'Seroquel Xr', 'US', 'H2-Pharma, LLC'),
  ('Quinapril', 'Accupril', 'US', NULL),
  ('Rabeprazole', 'Aciphex', 'US', 'Waylis Therapeutics LLC'),
  ('Ramelteon', 'Rozerem', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Ramipril', 'Altace', 'US', NULL),
  ('Ramucirumab', 'Cyramza', 'US', 'Eli Lilly and Company'),
  ('Ranitidine', 'Histac', 'GLOBAL', 'Sun Pharma'),
  ('Ranitidine', 'Ranidin', 'GLOBAL', 'Sami Pharmaceuticals'),
  ('Ranitidine', 'Zantac', 'GLOBAL', 'Haleon'),
  ('Ranolazine', 'Aspruzyo Sprinkle', 'US', 'SUN PHARMACEUTICAL INDUSTRIES, INC.'),
  ('Rasagiline', 'Azilect', 'US', 'Teva Neuroscience, Inc.'),
  ('Ravulizumab', 'Ultomiris', 'US', 'Alexion Pharmaceuticals Inc.'),
  ('Regadenoson', 'Lexiscan', 'US', 'Astellas Pharma US, Inc.'),
  ('Remifentanil', 'Ultiva', 'US', 'Mylan Institutional LLC'),
  ('Revefenacin', 'Yupelri', 'US', 'Viatris Specialty LLC'),
  ('Rifampin', 'Rifadin Iv', 'US', 'Sanofi-Aventis U.S. LLC'),
  ('Risankizumab-Rzaa', 'Skyrizi', 'US', 'AbbVie Inc.'),
  ('Risedronate', 'Actonel', 'US', NULL),
  ('Risperidone', 'Risperdal', 'US', 'Janssen Pharmaceuticals, Inc.'),
  ('Risperidone', 'Risperdal M-Tab', 'US', 'Janssen Pharmaceuticals, Inc.'),
  ('Risperidone', 'Uzedy', 'US', 'Teva Pharmaceuticals USA, Inc.'),
  ('Rituximab', 'Rituxan', 'US', 'Genentech, Inc.'),
  ('Rituximab-Abbs', 'Truxima', 'US', 'Cephalon, Inc.'),
  ('Rituximab-Arrx', 'Riabni', 'US', 'Amgen, Inc'),
  ('Rituximab-Pvvr', 'Ruxience', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Rivaroxaban', 'Xarelto', 'US', 'Janssen Pharmaceuticals, Inc.'),
  ('Rivastigmine', 'Exelon', 'US', 'Sandoz Inc'),
  ('Rizatriptan Benzoate', 'Maxalt', 'US', 'Organon LLC'),
  ('Rizatriptan Benzoate', 'Maxalt-Mlt', 'US', 'Organon LLC'),
  ('Rizatriptan Benzoate', 'Rizafilm', 'US', 'Gensco Laboratories LLC'),
  ('Roflumilast', 'Daliresp', 'US', 'AstraZeneca Pharmaceuticals LP'),
  ('Roflumilast', 'Zoryve', 'US', 'Arcutis Biotherapeutics, Inc.'),
  ('Romiplostim', 'Nplate', 'US', 'Amgen, Inc'),
  ('Ropeginterferon Alfa-2B', 'Besremi', 'US', 'PharmaEssentia USA'),
  ('Ropeginterferon Alfa-2B', 'Besremi Pen', 'US', 'PharmaEssentia USA'),
  ('Ropivacaine', 'Naropin', 'US', 'Fresenius Kabi USA, LLC'),
  ('Rosiglitazone', 'Avandia', 'US', NULL),
  ('Rosuvastatin', 'Crestor', 'US', 'AstraZeneca Pharmaceuticals LP'),
  ('Rotigotine', 'Neupro', 'US', 'UCB, Inc.'),
  ('Rozanolixizumab', 'Rystiggo', 'US', 'UCB, Inc.'),
  ('Salbutamol', 'Asthalin', 'GLOBAL', 'Cipla'),
  ('Salbutamol', 'ProAir', 'GLOBAL', 'Teva'),
  ('Salbutamol', 'Ventolin', 'GLOBAL', 'GSK'),
  ('Salicylic Acid', 'Acne Buster', 'US', 'Hangzhou Caring Cleaning Commodity Co., Ltd'),
  ('Salicylic Acid', 'Medicated Apricot Scrub', 'US', 'Rite Aid Corporation'),
  ('Salicylic Acid', 'Wart Remover', 'US', 'Guangzhou Hechuang Commercial Service Co.,Ltd.'),
  ('Salmeterol', 'Serevent Diskus', 'US', 'GlaxoSmithKline LLC'),
  ('Salsalate', 'Disalcid', 'US', NULL),
  ('Sargramostim', 'Leukine', 'US', 'Partner Therapeutics, Inc.'),
  ('Sarilumab', 'Kevzara', 'US', 'Sanofi-Aventis U.S. LLC'),
  ('Satralizumab', 'Enspryng', 'US', 'Genentech, Inc.'),
  ('Saxagliptin', 'Onglyza', 'US', NULL),
  ('Scopolamine', 'Transderm Scop', 'US', 'Baxter Healthcare Corporation'),
  ('Secukinumab', 'Cosentyx', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Selenium Sulfide', 'Careone Medicated Dandruff', 'US', 'Retail Business Services, LLC'),
  ('Selenium Sulfide', 'Cvs Gold', 'US', 'Apollo Health and Beauty Care'),
  ('Selenium Sulfide', 'Equate Medicated Dandruff Anti-Dandruff', 'US', 'Wal-Mart Stores, Inc.'),
  ('Semaglutide', 'Ozempic', 'US', 'Novo Nordisk Pharmaceutical Industries, LP'),
  ('Semaglutide', 'Rybelsus', 'US', 'Novo Nordisk Pharmaceutical Industries, LP'),
  ('Semaglutide', 'Wegovy', 'US', 'Novo Nordisk Pharmaceutical Industries, LP'),
  ('Senna', 'Ex-Lax', 'GLOBAL', 'Haleon'),
  ('Senna', 'Sennalax', 'GLOBAL', 'Sami Pharmaceuticals'),
  ('Senna', 'Senokot', 'GLOBAL', 'Reckitt'),
  ('Sertraline', 'Zoloft', 'US', 'Viatris Specialty LLC'),
  ('Sevoflurane', 'Sojourn', 'US', 'Piramal Critical Care Inc'),
  ('Sevoflurane', 'Ultane', 'US', 'AbbVie Inc.'),
  ('Sildenafil', 'Revatio', 'US', 'Viatris Specialty LLC'),
  ('Sildenafil', 'Viagra', 'US', 'Viatris Specialty LLC'),
  ('Sildenafil', 'Vybrique', 'US', 'IBSA Pharma Inc.'),
  ('Siltuximab', 'Sylvant', 'US', 'Recordati Rare Diseases, Inc.'),
  ('Simvastatin', 'Zocor', 'US', 'Organon LLC'),
  ('Sirolimus', 'Fyarro', 'US', 'Aadi Bioscience, Inc.'),
  ('Sirolimus', 'Hyftor', 'US', 'Nobelpharma America, LLC'),
  ('Sitagliptin', 'Istavel', 'GLOBAL', 'Sun Pharma'),
  ('Sitagliptin', 'Januvia', 'GLOBAL', 'MSD'),
  ('Sitagliptin', 'Sitaget', 'GLOBAL', 'Getz Pharma'),
  ('Sodium Borate', 'Borax', 'US', 'Boiron'),
  ('Sodium Borate', 'Borax 200Ck', 'US', 'SEVENE USA'),
  ('Sodium Sulfacetamide', 'Ovace Plus', 'US', 'Mission Pharmacal Company'),
  ('Sotalol', 'Betapace', 'US', 'Legacy Pharma USA, Inc.'),
  ('Sotalol', 'Betapace Af', 'US', 'Legacy Pharma USA, Inc.'),
  ('Sotalol', 'Sotylize', 'US', 'Azurity Pharmaceuticals, Inc.'),
  ('Spesolimab', 'Spevigo', 'US', 'LEO Pharma Inc.'),
  ('Spesolimab-Sbzo', 'Spevigo', 'US', 'Boehringer Ingelheim Pharmaceuticals, Inc.'),
  ('Spironolactone', 'Aldactone', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Sugammadex', 'Bridion', 'US', 'Merck Sharp & Dohme LLC'),
  ('Sulfacetamide', 'Klaron', 'US', 'Bausch Health US, LLC'),
  ('Sulfacetamide', 'Ovace', 'US', 'Mission Pharmacal Company'),
  ('Sulfacetamide', 'Ovace Plus', 'US', 'Mission Pharmacal Company'),
  ('Sulindac', 'Clinoril', 'US', NULL),
  ('Sumatriptan', 'Imitrex', 'US', 'GlaxoSmithKline LLC'),
  ('Sumatriptan', 'Tosymra', 'US', 'Upsher-Smith Laboratories, LLC'),
  ('Sumatriptan', 'Zembrace Symtouch', 'US', 'Upsher-Smith laboratories, LLC'),
  ('Sunitinib Malate', 'Sutent', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Tacrolimus', 'Envarsus Xr', 'US', 'Veloxis Pharmaceuticals, Inc'),
  ('Tacrolimus', 'Prograf', 'US', 'Astellas Pharma US, Inc.'),
  ('Tadalafil', 'Adcirca', 'US', 'United Therapeutics Corporation'),
  ('Tadalafil', 'Alyq', 'US', 'Teva Pharmaceuticals, Inc.'),
  ('Tadalafil', 'Cialis', 'US', 'Eli Lilly and Company'),
  ('Tafluprost', 'Zioptan', 'US', 'Thea Pharma Inc.'),
  ('Tamoxifen', 'Soltamox', 'US', 'Mayne Pharma'),
  ('Tazarotene', 'Arazlo', 'US', 'Bausch Health US, LLC'),
  ('Tazarotene', 'Fabior', 'US', 'Mayne Pharma'),
  ('Tazarotene', 'Tazorac', 'US', 'Almirall, LLC'),
  ('Tbo-Filgrastim', 'Granix', 'US', 'Cephalon, LLC'),
  ('Temazepam', 'Restoril', 'US', 'SpecGx LLC'),
  ('Temozolomide', 'Temodar', 'US', 'Merck Sharp & Dohme LLC'),
  ('Terazosin', 'Tezruly', 'US', 'ANI Pharmaceuticals, Inc.'),
  ('Terbinafine', 'Athletes Foot', 'US', 'H E B'),
  ('Terbinafine', 'Good Neighbor Pharmacy', 'US', 'Preferred Pharmaceuticals Inc.'),
  ('Terbinafine', 'Lamisil At Cream', 'US', 'Karo Healthcare Inc.'),
  ('Teriflunomide', 'Aubagio', 'US', 'Genzyme Corporation'),
  ('Testosterone', 'Vogelxo', 'US', 'Upsher-Smith Laboratories, LLC'),
  ('Testosterone', 'Xyosted', 'US', 'Antares Pharma, Inc.'),
  ('Testosterone Cypionate', 'Azmiro', 'US', 'Azurity Pharmaceuticals, Inc.'),
  ('Testosterone Cypionate', 'Depo-Testosterone', 'US', 'Pharmacia & Upjohn Company LLC'),
  ('Testosterone Undecanoate', 'Aveed', 'US', 'Endo USA, Inc.'),
  ('Testosterone Undecanoate', 'Jatenzo', 'US', 'TOLMAR Inc.'),
  ('Testosterone Undecanoate', 'Kyzatrex', 'US', 'Marius Pharmaceuticals'),
  ('Tetracaine', 'Blt 3', 'US', 'CENTURA PHARMACEUTICALS INC'),
  ('Tetracaine', 'Neuromed Topical Analgesic La', 'US', 'Sambria Pharmaceuticals, Inc.'),
  ('Tetracaine', 'Painless Tattoo 3', 'US', 'Sambria Pharmaceuticals, LLC'),
  ('Tetracycline', 'Viabecline', 'US', 'Accuria, LLC'),
  ('Tetracycline', 'Vitastem', 'US', 'ViaDerma Distribution, Inc.'),
  ('Tetracycline', 'Vitastem First Aid Antibiotic', 'US', 'VIADERMA DISTRIBUTION INC'),
  ('Tetrahydrozoline', 'Best Choice Eye Drops Original', 'US', 'Valu Merchandisers Company'),
  ('Tetrahydrozoline', 'Circle K Sterile Eye Drops', 'US', 'Lil'' Drug Store Products, Inc.'),
  ('Tetrahydrozoline', 'Cvp Sterile Eye Drops', 'US', 'Salado Sales, Inc.'),
  ('Tezepelumab-Ekko', 'Tezspire', 'US', 'Amgen Inc'),
  ('Theophylline', 'Theo-24', 'US', 'ENDO USA, Inc.'),
  ('Thiotepa', 'Tepadina', 'US', 'Amneal Pharmaceuticals LLC'),
  ('Thiotepa', 'Tepylute', 'US', 'Shorla Oncology Inc.'),
  ('Thyrotropin Alfa', 'Thyrogen', 'US', 'Genzyme Corporation'),
  ('Ticagrelor', 'Brilinta', 'US', 'AstraZeneca Pharmaceuticals LP'),
  ('Tigecycline', 'Tygacil', 'US', 'Wyeth Pharmaceuticals LLC, a subsidiary of Pfizer Inc.'),
  ('Timolol', 'Betimol', 'US', 'Thea Pharma Inc.'),
  ('Timolol', 'Timoptic', 'US', 'Bausch & Lomb Incorporated'),
  ('Timolol', 'Timoptic In Ocudose', 'US', 'Bausch & Lomb Incorporated'),
  ('Tioconazole', 'Vagistat', 'US', 'Combe Incorporated'),
  ('Tiotropium', 'Spiriva Handihaler', 'US', 'A-S Medication Solutions'),
  ('Tiotropium', 'Spiriva Respimat', 'US', 'Boehringer Ingelheim Pharmaceuticals, Inc.'),
  ('Tirofiban', 'Aggrastat', 'US', 'Medicure International Inc'),
  ('Tislelizumab-Jsgr', 'Tevimbra', 'US', 'BeOne Medicines USA, Inc.'),
  ('Tizanidine', 'Ontralfy', 'US', 'Rosemont Pharmaceuticals, LLC'),
  ('Tizanidine', 'Zanaflex', 'US', 'Legacy Pharma USA, Inc.'),
  ('Tobramycin', 'Bethkis', 'US', 'Chiesi USA, Inc.'),
  ('Tobramycin', 'Bethkis', 'US', 'Chiesi USA, Inc.'),
  ('Tobramycin', 'Kitabis Pak', 'US', 'Pari Respiratory Equipment, Inc.'),
  ('Tobramycin', 'Kitabis Pak', 'US', 'Pari Respiratory Equipment, Inc.'),
  ('Tobramycin', 'Tobi', 'US', 'Viatris Specialty LLC'),
  ('Tobramycin', 'Tobi', 'US', 'Viatris Specialty LLC'),
  ('Tocilizumab', 'Actemra', 'US', 'Genentech, Inc.'),
  ('Tocilizumab', 'Avtozma', 'US', 'CELLTRION USA, Inc.'),
  ('Tocilizumab', 'Tofidence', 'US', 'Organon LLC'),
  ('Tocilizumab-Aazg', 'Tyenne', 'US', 'Fresenius Kabi USA, LLC'),
  ('Tofacitinib', 'Xeljanz', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Tofacitinib', 'Xeljanz Xr', 'US', 'U.S. Pharmaceuticals'),
  ('Tolmetin', 'Tolectin', 'US', 'Poly Pharmaceuticals, Inc.'),
  ('Tolnaftate', 'Antifungal Liquid', 'US', 'Target Corporation'),
  ('Tolnaftate', 'Antifungal Liquid', 'US', 'Target Corporation'),
  ('Tolnaftate', 'Maximum Strength Antifungal Liquid', 'US', 'Chain Drug Marketing Association Inc'),
  ('Tolnaftate', 'Maximum Strength Antifungal Liquid', 'US', 'Chain Drug Marketing Association Inc'),
  ('Tolnaftate', 'Tolnafate', 'US', 'Meijer Distribution Inc.'),
  ('Tolnaftate', 'Tolnafate', 'US', 'Meijer Distribution Inc.'),
  ('Tolterodine', 'Detrol', 'US', 'Viatris Specialty LLC'),
  ('Topiramate', 'Qudexy Xr', 'US', 'Upsher-Smith Laboratories, LLC'),
  ('Topiramate', 'Topamax', 'US', 'Janssen Pharmaceuticals, Inc.'),
  ('Topiramate', 'Trokendi Xr', 'US', 'Supernus Pharmaceuticals, Inc.'),
  ('Topotecan', 'Hycamtin', 'US', 'Sandoz Inc'),
  ('Torsemide', 'Soaanz', 'US', 'Sarfez Pharmaceuticals Inc'),
  ('Tralokinumab-Ldrm', 'Adbry', 'US', 'LEO Pharma Inc.'),
  ('Tramadol', 'Conzip', 'US', 'Vertical Pharmaceuticals, LLC'),
  ('Trandolapril', 'Mavik', 'US', NULL),
  ('Tranexamic Acid', 'Cyklokapron', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Trastuzumab', 'Herceptin', 'US', 'Genentech, Inc.'),
  ('Trastuzumab', 'Herzuma', 'US', 'Cephalon, Inc.'),
  ('Trastuzumab', 'Ogivri', 'US', 'Mylan Institutional LLC'),
  ('Trastuzumab-Anns', 'Kanjinti', 'US', 'Amgen, Inc'),
  ('Trastuzumab-Dkst', 'Ogivri', 'US', 'Biocon Biologics Inc.'),
  ('Trastuzumab-Strf', 'Hercessi', 'US', 'Accord BioPharma Inc.'),
  ('Travoprost', 'Travatan Z', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Trazodone', 'Raldesy Tm', 'US', 'Validus Pharmaceuticals LLC'),
  ('Tretinoin', 'Altreno', 'US', 'Bausch Health US, LLC'),
  ('Tretinoin', 'Retin-A', 'US', 'Bausch Health US, LLC'),
  ('Tretinoin', 'Retin-A Micro', 'US', 'Bausch Health US LLC'),
  ('Triamcinolone Acetonide', 'Kenalog-40', 'US', 'A-S Medication Solutions'),
  ('Triamcinolone Acetonide', 'Nasal Allergy', 'US', 'Rugby Laboratories'),
  ('Triamcinolone Acetonide', 'Triderm', 'US', 'Crown Laboratories'),
  ('Triamterene', 'Dyrenium', 'US', 'Advanz Pharma (US) Corp.'),
  ('Triclosan', 'Digiclean E', 'US', 'Ecolab Inc.'),
  ('Triclosan', 'Ecocare 250', 'US', 'Ecolab Inc.'),
  ('Triclosan', 'Ecolab', 'US', 'Ecolab Inc.'),
  ('Trilaciclib', 'Cosela', 'US', 'G1 Therapeutics, Inc.'),
  ('Trimethobenzamide', 'Tigan', 'US', 'Par Health USA, LLC'),
  ('Tropicamide', 'Mydriacyl', 'US', 'Alcon Laboratories, Inc.'),
  ('Undecylenic Acid', 'Antifungal Pen', 'US', 'Guangzhou Mizi Biotechnology Co., Ltd.'),
  ('Undecylenic Acid', 'Fungal Nail Patches', 'US', 'Guangzhou Hechuang Commercial Service Co.,Ltd.'),
  ('Undecylenic Acid', 'Hongo Killer', 'US', 'Efficient Laboratories Inc'),
  ('Ustekinumab', 'Stelara', 'US', 'Janssen Biotech, Inc.'),
  ('Ustekinumab', 'Yesintek', 'US', 'Biocon Biologics Inc.'),
  ('Ustekinumab-Aauz', 'Otulfi', 'US', 'Fresenius Kabi USA, LLC'),
  ('Ustekinumab-Aekn', 'Selarsdi', 'US', 'Teva Pharmaceuticals USA, Inc.'),
  ('Ustekinumab-Auub', 'Wezlana', 'US', 'Nuvaila Limited'),
  ('Ustekinumab-Hmny', 'Starjemza', 'US', 'Hikma Pharmaceuticals USA Inc.'),
  ('Ustekinumab-Srlf', 'Imuldosa', 'US', 'Accord BioPharma Inc.'),
  ('Ustekinumab-Stba', 'Steqeyma', 'US', 'CELLTRION USA, Inc.'),
  ('Ustekinumab-Ttwe', 'Pyzchiva', 'US', 'SANDOZ INC'),
  ('Valsartan', 'Diovan', 'US', 'Novartis Pharmaceuticals Corporation'),
  ('Vancomycin', 'Tyzavan', 'US', 'Hikma Pharmaceuticals USA Inc.'),
  ('Vancomycin', 'Vancocin', 'US', 'ANI Pharmaceuticals, Inc.'),
  ('Varenicline', 'Chantix', 'US', 'Pfizer Laboratories Div Pfizer Inc'),
  ('Varenicline', 'Tyrvaya', 'US', 'Oyster Point Pharma, Inc.'),
  ('Vedolizumab', 'Entyvio', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Vedolizumab', 'Entyvio Pen', 'US', 'Takeda Pharmaceuticals America, Inc.'),
  ('Venlafaxine', 'Effexor Xr', 'US', 'Viatris Specialty LLC'),
  ('Verapamil', 'Calan', 'US', NULL),
  ('Verapamil', 'Isoptin', 'US', NULL),
  ('Vigabatrin', 'Sabril', 'US', 'Lundbeck Pharmaceuticals LLC'),
  ('Vigabatrin', 'Vigadrone', 'US', 'Upsher-Smith Laboratories, LLC'),
  ('Vigabatrin', 'Vigafyde', 'US', 'Upsher-Smith Laboratories, LLC'),
  ('Vilazodone', 'Viibryd', 'US', 'Allergan, Inc.'),
  ('Voriconazole', 'Vfend', 'US', 'Roerig'),
  ('Warfarin', 'Jantoven', 'US', 'Upsher-Smith Laboratories, LLC'),
  ('Xylometazoline', 'Metarivin Soln. 0.1%', 'US', 'Lydia Co., Ltd.'),
  ('Zanamivir', 'Relenza', 'US', 'GlaxoSmithKline LLC'),
  ('Zavegepant', 'Zavzpret', 'US', 'U.S. Pharmaceuticals'),
  ('Zilucoplan', 'Zilbrysq', 'US', 'UCB, Inc.'),
  ('Zinc Oxide Sunscreen', 'Binda Face And Body Sunscreen Spf50', 'US', 'VEGANIC SKN LIMITED'),
  ('Zinc Oxide Sunscreen', 'Ecozinc Natural Mineral Sunscreen Spf50', 'US', 'VEGANIC SKN LIMITED'),
  ('Zinc Oxide Sunscreen', 'Eltamd Uv Aox Mist', 'US', 'CP Skin Health Group, Inc'),
  ('Zinc Pyrithione', 'Anti-Dandruff', 'US', 'MEERAY COSMETICS CO., LTD.'),
  ('Zinc Pyrithione', 'Balancing', 'US', 'Zero Flakes Given, Inc.'),
  ('Zinc Pyrithione', 'Dandrx Anti-Dandruff', 'US', 'dandRX LLC'),
  ('Zincum Gluconicum', 'Rite Aid Zinc Cold Therapy', 'US', 'RITE AID CORPORATION'),
  ('Ziprasidone', 'Geodon', 'US', 'ROERIG'),
  ('Ziv-Aflibercept', 'Zaltrap', 'US', 'sanofi-aventis U.S. LLC'),
  ('Zoledronic Acid', 'Reclast', 'US', 'Sandoz Inc'),
  ('Zolmitriptan', 'Zolmiptriptan', 'US', 'Glenmark Pharmaceuticals Inc., USA'),
  ('Zolmitriptan', 'Zomig', 'US', 'Amneal Pharmaceuticals LLC'),
  ('Zolpidem', 'Ambien', 'US', 'Sanofi-Aventis U.S. LLC'),
  ('Zolpidem', 'Ambien Cr', 'US', 'Cosette Pharmaceuticals, Inc.'),
  ('Zolpidem', 'Edluar', 'US', 'Viatris Specialty LLC'),
  ('Zonisamide', 'Zonegran', 'US', 'Advanz Pharma (US) Corp.'),
  ('Zonisamide', 'Zonisade', 'US', 'Azurity Pharmaceuticals, Inc.')
) AS v(generic, brand, market, manufacturer)
JOIN public.drugs d ON lower(d.name) = lower(v.generic)
ON CONFLICT (drug_id, brand, market)
DO UPDATE SET manufacturer = EXCLUDED.manufacturer;
