-- Institution and educator platform.
--
-- Adds the educator role, the class structures behind it, and the row-level
-- policies that keep one educator's cohort invisible to another.
--
-- The isolation rule this file enforces, stated once: an educator may read a
-- student's data only while that student is enrolled in a class the educator
-- owns. Not "is an educator" - owning the class is what grants it, so
-- unenrolling a student ends the access with no other action.

-- ---------------------------------------------------------------------------
-- 1. The role
-- ---------------------------------------------------------------------------

-- Guarded exactly as 'admin' was when it was added, since ALTER TYPE ... ADD
-- VALUE cannot run twice and cannot be rolled back inside a transaction.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_enum
    WHERE enumlabel = 'educator'
      AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'user_role')
  ) THEN
    ALTER TYPE public.user_role ADD VALUE 'educator';
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 2. Tables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.institutions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL CHECK (length(btrim(name)) > 0),
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.classes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_id uuid REFERENCES public.institutions(id) ON DELETE SET NULL,
  educator_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL CHECK (length(btrim(name)) > 0),
  -- Typed by a student on signup, so it avoids characters that are ambiguous
  -- in most fonts: no O/0, no I/1. Generated by the app, unique here.
  join_code text NOT NULL UNIQUE CHECK (join_code ~ '^[A-HJ-NP-Z2-9]{6}$'),
  archived boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS classes_educator_idx ON public.classes (educator_id);

CREATE TABLE IF NOT EXISTS public.class_enrollments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  class_id uuid NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  student_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  enrolled_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (class_id, student_id)
);
CREATE INDEX IF NOT EXISTS enrollments_student_idx ON public.class_enrollments (student_id);
CREATE INDEX IF NOT EXISTS enrollments_class_idx ON public.class_enrollments (class_id);

CREATE TABLE IF NOT EXISTS public.class_assignments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  class_id uuid NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  case_id uuid REFERENCES public.cases(id) ON DELETE CASCADE,
  -- Set where the assignment is a mode to practise rather than one stored case,
  -- which is most of them: generated cases have no row in `cases`.
  mode public.case_mode,
  title text,
  due_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (case_id IS NOT NULL OR mode IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS assignments_class_idx ON public.class_assignments (class_id, due_at);

CREATE TABLE IF NOT EXISTS public.assessments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  class_id uuid NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  title text NOT NULL CHECK (length(btrim(title)) > 0),
  mode public.case_mode NOT NULL,
  case_count integer NOT NULL DEFAULT 3 CHECK (case_count BETWEEN 1 AND 20),
  time_limit_sec integer NOT NULL DEFAULT 900 CHECK (time_limit_sec BETWEEN 60 AND 14400),
  opens_at timestamptz,
  closes_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS assessments_class_idx ON public.assessments (class_id);

-- One sitting. Created when a student opens the assessment and never reopened:
-- the row existing is what makes the attempt used up.
CREATE TABLE IF NOT EXISTS public.assessment_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  assessment_id uuid NOT NULL REFERENCES public.assessments(id) ON DELETE CASCADE,
  student_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  started_at timestamptz NOT NULL DEFAULT now(),
  submitted_at timestamptz,
  score integer,
  accuracy numeric(5,2),
  cases_done integer NOT NULL DEFAULT 0,
  UNIQUE (assessment_id, student_id)
);
CREATE INDEX IF NOT EXISTS assessment_sessions_student_idx ON public.assessment_sessions (student_id);

-- ---------------------------------------------------------------------------
-- 3. Helpers
--
-- SECURITY DEFINER on purpose. A policy on class_enrollments that itself
-- queries class_enrollments recurses; routing the lookup through a definer
-- function breaks that cycle, which is the same reason is_admin exists.
-- ---------------------------------------------------------------------------

-- role::text, not role = 'educator'. A LANGUAGE sql body is parsed when the
-- function is created, and resolving the literal against the enum in the same
-- transaction that added the value fails with "unsafe use of new value". The
-- text comparison never touches the enum, so the whole file can be run in one
-- go - which is how it is actually applied, pasted into the SQL editor.
CREATE OR REPLACE FUNCTION public.is_educator(uid uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles WHERE user_id = uid AND role::text = 'educator'
  );
$$;

/** Whether this educator owns the class. Ownership, not role, grants access. */
CREATE OR REPLACE FUNCTION public.owns_class(uid uuid, cls uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (SELECT 1 FROM public.classes WHERE id = cls AND educator_id = uid);
$$;

/** Whether the student is enrolled in any class this educator owns. */
CREATE OR REPLACE FUNCTION public.teaches_student(educator uuid, student uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.class_enrollments e
    JOIN public.classes c ON c.id = e.class_id
    WHERE e.student_id = student AND c.educator_id = educator AND NOT c.archived
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_educator(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.owns_class(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.teaches_student(uuid, uuid) TO authenticated;

-- ---------------------------------------------------------------------------
-- 4. Row level security
-- ---------------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON public.institutions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.classes TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.class_enrollments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.class_assignments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.assessments TO authenticated;
-- No UPDATE: a sitting is closed by submit_assessment_sitting(), never by the
-- student writing their own marks.
GRANT SELECT, INSERT ON public.assessment_sessions TO authenticated;
GRANT ALL ON public.institutions, public.classes, public.class_enrollments,
              public.class_assignments, public.assessments, public.assessment_sessions
  TO service_role;

ALTER TABLE public.institutions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessment_sessions ENABLE ROW LEVEL SECURITY;

-- Institutions: the educator who created it.
DROP POLICY IF EXISTS institutions_own ON public.institutions;
CREATE POLICY institutions_own ON public.institutions
  FOR ALL USING (auth.uid() = created_by OR public.is_admin(auth.uid()))
  WITH CHECK (auth.uid() = created_by);

-- Classes: the owning educator manages them. A student may read the classes
-- they are enrolled in, and nothing else - not the roll, not other classes.
DROP POLICY IF EXISTS classes_educator_all ON public.classes;
CREATE POLICY classes_educator_all ON public.classes
  FOR ALL USING (auth.uid() = educator_id OR public.is_admin(auth.uid()))
  WITH CHECK (auth.uid() = educator_id AND public.is_educator(auth.uid()));

DROP POLICY IF EXISTS classes_select_enrolled ON public.classes;
CREATE POLICY classes_select_enrolled ON public.classes
  FOR SELECT USING (EXISTS (
    SELECT 1 FROM public.class_enrollments e
    WHERE e.class_id = id AND e.student_id = auth.uid()
  ));

-- Enrolments: a student sees and creates only their own; the owning educator
-- sees and removes any in their class.
DROP POLICY IF EXISTS enrollments_student_own ON public.class_enrollments;
CREATE POLICY enrollments_student_own ON public.class_enrollments
  FOR SELECT USING (auth.uid() = student_id OR public.owns_class(auth.uid(), class_id));

DROP POLICY IF EXISTS enrollments_student_join ON public.class_enrollments;
CREATE POLICY enrollments_student_join ON public.class_enrollments
  FOR INSERT WITH CHECK (auth.uid() = student_id);

DROP POLICY IF EXISTS enrollments_leave ON public.class_enrollments;
CREATE POLICY enrollments_leave ON public.class_enrollments
  FOR DELETE USING (auth.uid() = student_id OR public.owns_class(auth.uid(), class_id));

-- Assignments and assessments: written by the owning educator, read by the
-- class.
DROP POLICY IF EXISTS assignments_educator ON public.class_assignments;
CREATE POLICY assignments_educator ON public.class_assignments
  FOR ALL USING (public.owns_class(auth.uid(), class_id))
  WITH CHECK (public.owns_class(auth.uid(), class_id));

DROP POLICY IF EXISTS assignments_read_enrolled ON public.class_assignments;
CREATE POLICY assignments_read_enrolled ON public.class_assignments
  FOR SELECT USING (EXISTS (
    SELECT 1 FROM public.class_enrollments e
    WHERE e.class_id = class_assignments.class_id AND e.student_id = auth.uid()
  ));

DROP POLICY IF EXISTS assessments_educator ON public.assessments;
CREATE POLICY assessments_educator ON public.assessments
  FOR ALL USING (public.owns_class(auth.uid(), class_id))
  WITH CHECK (public.owns_class(auth.uid(), class_id));

DROP POLICY IF EXISTS assessments_read_enrolled ON public.assessments;
CREATE POLICY assessments_read_enrolled ON public.assessments
  FOR SELECT USING (EXISTS (
    SELECT 1 FROM public.class_enrollments e
    WHERE e.class_id = assessments.class_id AND e.student_id = auth.uid()
  ));

-- Sittings: a student may create and finish their own, and never delete one.
-- No DELETE policy and no DELETE grant, so an attempt cannot be erased and
-- retaken.
DROP POLICY IF EXISTS assessment_sessions_student ON public.assessment_sessions;
CREATE POLICY assessment_sessions_student ON public.assessment_sessions
  FOR SELECT USING (
    auth.uid() = student_id
    OR EXISTS (
      SELECT 1 FROM public.assessments a
      WHERE a.id = assessment_id AND public.owns_class(auth.uid(), a.class_id)
    )
  );

DROP POLICY IF EXISTS assessment_sessions_start ON public.assessment_sessions;
CREATE POLICY assessment_sessions_start ON public.assessment_sessions
  FOR INSERT WITH CHECK (auth.uid() = student_id);

-- Deliberately no UPDATE policy. A student who could update their own sitting
-- could write their own score and accuracy into it, which is the one thing a
-- graded assessment cannot allow. Submission goes through
-- submit_assessment_sitting() below, which derives the result from the score
-- rows the game actually wrote.
DROP POLICY IF EXISTS assessment_sessions_finish ON public.assessment_sessions;

-- ---------------------------------------------------------------------------
-- 5. Reading student work
--
-- The two policies that actually make the platform work. Both are scoped by
-- teaches_student, so an educator sees a learner's rows only while that learner
-- is enrolled in one of their live classes - never another educator's cohort,
-- and never the whole database the way an admin can.
-- ---------------------------------------------------------------------------

DROP POLICY IF EXISTS scores_select_educator ON public.scores;
CREATE POLICY scores_select_educator ON public.scores
  FOR SELECT USING (public.teaches_student(auth.uid(), user_id));

DROP POLICY IF EXISTS profiles_select_educator ON public.profiles;
CREATE POLICY profiles_select_educator ON public.profiles
  FOR SELECT USING (public.teaches_student(auth.uid(), user_id));

-- ---------------------------------------------------------------------------
-- 6. Joining by code
--
-- A student needs to turn a code into a class id without being able to read
-- the classes table at large, which would let anyone enumerate every class in
-- the product. This returns one id for one exact code and nothing else.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.join_class_by_code(code text)
RETURNS uuid
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  target uuid;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not signed in';
  END IF;

  SELECT id INTO target
  FROM public.classes
  WHERE join_code = upper(btrim(code)) AND NOT archived;

  IF target IS NULL THEN
    RETURN NULL;
  END IF;

  INSERT INTO public.class_enrollments (class_id, student_id)
  VALUES (target, auth.uid())
  ON CONFLICT (class_id, student_id) DO NOTHING;

  RETURN target;
END;
$$;

REVOKE ALL ON FUNCTION public.join_class_by_code(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.join_class_by_code(text) TO authenticated;

-- ---------------------------------------------------------------------------
-- 7. Closing a sitting
--
-- The marks are computed here, from the score rows the game wrote during the
-- window, rather than sent up by the browser. Same evidence the rest of the
-- app grades from, and nothing the student can author.
--
-- Cases are taken in the order they were completed, capped at the number the
-- assessment asked for, and only up to the deadline - so overrunning the clock
-- cannot add a case, and neither can playing extra ones.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.submit_assessment_sitting(session_id uuid)
RETURNS TABLE (cases_done integer, score integer, accuracy numeric)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  sitting public.assessment_sessions;
  exam public.assessments;
  window_end timestamptz;
BEGIN
  SELECT * INTO sitting FROM public.assessment_sessions WHERE id = session_id;
  IF NOT FOUND OR sitting.student_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'Not your sitting';
  END IF;

  -- Idempotent: a retry after a dropped connection returns the stored result
  -- rather than recomputing it against a later, longer window.
  IF sitting.submitted_at IS NOT NULL THEN
    RETURN QUERY SELECT sitting.cases_done, sitting.score, sitting.accuracy;
    RETURN;
  END IF;

  SELECT * INTO exam FROM public.assessments WHERE id = sitting.assessment_id;
  window_end := least(now(), sitting.started_at + make_interval(secs => exam.time_limit_sec));

  WITH counted AS (
    SELECT s.score AS case_score, s.accuracy AS case_accuracy
    FROM public.scores s
    WHERE s.user_id = sitting.student_id
      AND s.mode = exam.mode
      AND s.completed_at >= sitting.started_at
      AND s.completed_at <= window_end
    ORDER BY s.completed_at
    LIMIT exam.case_count
  )
  UPDATE public.assessment_sessions t
  SET submitted_at = now(),
      cases_done   = (SELECT count(*) FROM counted),
      score        = COALESCE((SELECT round(sum(case_score)) FROM counted), 0),
      -- scores.accuracy is a fraction; this column is a percentage.
      accuracy     = COALESCE((SELECT round(avg(case_accuracy) * 100, 2) FROM counted), 0)
  WHERE t.id = session_id;

  RETURN QUERY
    SELECT t.cases_done, t.score, t.accuracy
    FROM public.assessment_sessions t
    WHERE t.id = session_id;
END;
$$;

REVOKE ALL ON FUNCTION public.submit_assessment_sitting(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.submit_assessment_sitting(uuid) TO authenticated;
