-- Real medicines, replacing generated placeholders.
--
-- Extracted from a pharmacy reference and then curated: only the factual
-- layer (generic name, brand, class) is taken, because facts are not
-- copyrightable while prose is. Drug class was assigned deliberately rather
-- than scraped - heading detection in the source produced wrong answers such
-- as acebutolol under "Nitrates".
--
-- Doses are deliberately NOT loaded. Extraction merged adjacent table columns
-- roughly four times in five, producing strings like
-- "10 mg daily PO or 70 mg 5.0 mg PO daily or 35". A wrong dose in a training
-- product is the most harmful thing it could contain, so the column is left
-- empty and marked for pharmacist verification rather than filled with
-- something plausible.

-- Brands vary by market, so they are a separate table rather than a column.
-- The same molecule is Lasix in the US and something else locally; the brand
-- step should teach whichever market the learner is training for.
CREATE TABLE IF NOT EXISTS public.drug_brands (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  drug_id uuid NOT NULL REFERENCES public.drugs(id) ON DELETE CASCADE,
  brand text NOT NULL,
  market text NOT NULL DEFAULT 'US',
  manufacturer text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (drug_id, brand, market)
);
CREATE INDEX IF NOT EXISTS drug_brands_drug_idx ON public.drug_brands (drug_id);
CREATE INDEX IF NOT EXISTS drug_brands_market_idx ON public.drug_brands (market);

GRANT SELECT ON public.drug_brands TO authenticated, anon;
GRANT ALL ON public.drug_brands TO service_role;
ALTER TABLE public.drug_brands ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS drug_brands_select_all ON public.drug_brands;
CREATE POLICY drug_brands_select_all ON public.drug_brands FOR SELECT USING (true);

-- Marks a row as awaiting clinical review, so unverified entries can be told
-- apart from checked ones in the UI rather than all looking equally reliable.
ALTER TABLE public.drugs ADD COLUMN IF NOT EXISTS needs_review boolean NOT NULL DEFAULT false;

-- Upsert on name so re-running refreshes rather than duplicating.
INSERT INTO public.drugs (name, generic_name, drug_class, category, needs_review)
SELECT v.name, v.generic_name, v.drug_class, v.category, true
FROM (VALUES
  ('Abatacept', 'Abatacept', 'Selective T-cell Costimulation Modulator', 'Immunology'),
  ('Abciximab', 'Abciximab', 'Glycoprotein IIb/IIIa Inhibitor', 'Cardiovascular'),
  ('Acarbose', 'Acarbose', 'Alpha-glucosidase Inhibitor', 'Antidiabetic'),
  ('Acebutolol', 'Acebutolol', 'Beta-blocker', 'Cardiovascular'),
  ('Adalimumab', 'Adalimumab', 'TNF Inhibitor', 'Immunology'),
  ('Alendronate', 'Alendronate', 'Bisphosphonate', 'Supplement'),
  ('Amiloride', 'Amiloride', 'Potassium-sparing Diuretic', 'Cardiovascular'),
  ('Amlodipine', 'Amlodipine', 'Calcium Channel Blocker', 'Cardiovascular'),
  ('Anakinra', 'Anakinra', 'IL-1 Receptor Antagonist', 'Immunology'),
  ('Atenolol', 'Atenolol', 'Beta-blocker', 'Cardiovascular'),
  ('Azathioprine', 'Azathioprine', 'Purine Antimetabolite', 'Immunology'),
  ('Basiliximab', 'Basiliximab', 'IL-2 Receptor Antagonist', 'Immunology'),
  ('Benazepril', 'Benazepril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Betaxolol', 'Betaxolol', 'Beta-blocker', 'Cardiovascular'),
  ('Bisoprolol', 'Bisoprolol', 'Beta-blocker', 'Cardiovascular'),
  ('Bromocriptine', 'Bromocriptine', 'Dopamine Agonist', 'Psychiatric'),
  ('Candesartan', 'Candesartan', 'ARB', 'Cardiovascular'),
  ('Captopril', 'Captopril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Carvedilol', 'Carvedilol', 'Beta-blocker', 'Cardiovascular'),
  ('Celecoxib', 'Celecoxib', 'COX-2 Inhibitor', 'Analgesic'),
  ('Certolizumab', 'Certolizumab', 'TNF Inhibitor', 'Immunology'),
  ('Chlorothiazide', 'Chlorothiazide', 'Thiazide Diuretic', 'Cardiovascular'),
  ('Citalopram', 'Citalopram', 'SSRI', 'Psychiatric'),
  ('Clomipramine', 'Clomipramine', 'Tricyclic Antidepressant', 'Psychiatric'),
  ('Clonidine', 'Clonidine', 'Central Alpha-2 Agonist', 'Cardiovascular'),
  ('Colesevelam', 'Colesevelam', 'Bile Acid Sequestrant', 'Cardiovascular'),
  ('Cyclosporine', 'Cyclosporine', 'Calcineurin Inhibitor', 'Immunology'),
  ('Diclofenac', 'Diclofenac', 'NSAID', 'Analgesic'),
  ('Diltiazem', 'Diltiazem', 'Calcium Channel Blocker', 'Cardiovascular'),
  ('Duloxetine', 'Duloxetine', 'SNRI', 'Psychiatric'),
  ('Enalapril', 'Enalapril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Eplerenone', 'Eplerenone', 'Aldosterone Antagonist', 'Cardiovascular'),
  ('Etanercept', 'Etanercept', 'TNF Inhibitor', 'Immunology'),
  ('Everolimus', 'Everolimus', 'mTOR Inhibitor', 'Immunology'),
  ('Exenatide', 'Exenatide', 'GLP-1 Agonist', 'Antidiabetic'),
  ('Felodipine', 'Felodipine', 'Calcium Channel Blocker', 'Cardiovascular'),
  ('Fluoxetine', 'Fluoxetine', 'SSRI', 'Psychiatric'),
  ('Fosinopril', 'Fosinopril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Furosemide', 'Furosemide', 'Loop Diuretic', 'Cardiovascular'),
  ('Gabapentin', 'Gabapentin', 'Anticonvulsant', 'Psychiatric'),
  ('Glimepiride', 'Glimepiride', 'Sulfonylurea', 'Antidiabetic'),
  ('Golimumab', 'Golimumab', 'TNF Inhibitor', 'Immunology'),
  ('Hydrochlorothiazide', 'Hydrochlorothiazide', 'Thiazide Diuretic', 'Cardiovascular'),
  ('Ibandronate', 'Ibandronate', 'Bisphosphonate', 'Supplement'),
  ('Ibuprofen', 'Ibuprofen', 'NSAID', 'Analgesic'),
  ('Infliximab', 'Infliximab', 'TNF Inhibitor', 'Immunology'),
  ('Isradipine', 'Isradipine', 'Calcium Channel Blocker', 'Cardiovascular'),
  ('Labetalol', 'Labetalol', 'Alpha/Beta-blocker', 'Cardiovascular'),
  ('Lactulose', 'Lactulose', 'Osmotic Laxative', 'GI'),
  ('Leflunomide', 'Leflunomide', 'DMARD', 'Immunology'),
  ('Linagliptin', 'Linagliptin', 'DPP-4 Inhibitor', 'Antidiabetic'),
  ('Liraglutide', 'Liraglutide', 'GLP-1 Agonist', 'Antidiabetic'),
  ('Lisinopril', 'Lisinopril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Losartan', 'Losartan', 'ARB', 'Cardiovascular'),
  ('Methyldopa', 'Methyldopa', 'Central Alpha-2 Agonist', 'Cardiovascular'),
  ('Metolazone', 'Metolazone', 'Thiazide-like Diuretic', 'Cardiovascular'),
  ('Metoprolol', 'Metoprolol', 'Beta-blocker', 'Cardiovascular'),
  ('Miglitol', 'Miglitol', 'Alpha-glucosidase Inhibitor', 'Antidiabetic'),
  ('Minocycline', 'Minocycline', 'Tetracycline', 'Antibiotic'),
  ('Nabumetone', 'Nabumetone', 'NSAID', 'Analgesic'),
  ('Nadolol', 'Nadolol', 'Beta-blocker', 'Cardiovascular'),
  ('Naproxen', 'Naproxen', 'NSAID', 'Analgesic'),
  ('Nateglinide', 'Nateglinide', 'Meglitinide', 'Antidiabetic'),
  ('Nicardipine', 'Nicardipine', 'Calcium Channel Blocker', 'Cardiovascular'),
  ('Nisoldipine', 'Nisoldipine', 'Calcium Channel Blocker', 'Cardiovascular'),
  ('Paroxetine', 'Paroxetine', 'SSRI', 'Psychiatric'),
  ('Perindopril', 'Perindopril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Pioglitazone', 'Pioglitazone', 'Thiazolidinedione', 'Antidiabetic'),
  ('Pramlintide', 'Pramlintide', 'Amylin Analogue', 'Antidiabetic'),
  ('Propranolol', 'Propranolol', 'Beta-blocker', 'Cardiovascular'),
  ('Quinapril', 'Quinapril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Ramipril', 'Ramipril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Risedronate', 'Risedronate', 'Bisphosphonate', 'Supplement'),
  ('Rituximab', 'Rituximab', 'CD20 Monoclonal Antibody', 'Oncology'),
  ('Rosiglitazone', 'Rosiglitazone', 'Thiazolidinedione', 'Antidiabetic'),
  ('Salsalate', 'Salsalate', 'Salicylate', 'Analgesic'),
  ('Saxagliptin', 'Saxagliptin', 'DPP-4 Inhibitor', 'Antidiabetic'),
  ('Sertraline', 'Sertraline', 'SSRI', 'Psychiatric'),
  ('Sitagliptin', 'Sitagliptin', 'DPP-4 Inhibitor', 'Antidiabetic'),
  ('Spironolactone', 'Spironolactone', 'Aldosterone Antagonist', 'Cardiovascular'),
  ('Sulindac', 'Sulindac', 'NSAID', 'Analgesic'),
  ('Tacrolimus', 'Tacrolimus', 'Calcineurin Inhibitor', 'Immunology'),
  ('Tocilizumab', 'Tocilizumab', 'IL-6 Receptor Antagonist', 'Immunology'),
  ('Tolmetin', 'Tolmetin', 'NSAID', 'Analgesic'),
  ('Torsemide', 'Torsemide', 'Loop Diuretic', 'Cardiovascular'),
  ('Trandolapril', 'Trandolapril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Triamterene', 'Triamterene', 'Potassium-sparing Diuretic', 'Cardiovascular'),
  ('Valsartan', 'Valsartan', 'ARB', 'Cardiovascular'),
  ('Venlafaxine', 'Venlafaxine', 'SNRI', 'Psychiatric'),
  ('Verapamil', 'Verapamil', 'Calcium Channel Blocker', 'Cardiovascular')
) AS v(name, generic_name, drug_class, category)
WHERE NOT EXISTS (
  SELECT 1 FROM public.drugs d WHERE lower(d.name) = lower(v.name)
);

UPDATE public.drugs d
SET drug_class = v.drug_class, category = v.category
FROM (VALUES
  ('Abatacept', 'Abatacept', 'Selective T-cell Costimulation Modulator', 'Immunology'),
  ('Abciximab', 'Abciximab', 'Glycoprotein IIb/IIIa Inhibitor', 'Cardiovascular'),
  ('Acarbose', 'Acarbose', 'Alpha-glucosidase Inhibitor', 'Antidiabetic'),
  ('Acebutolol', 'Acebutolol', 'Beta-blocker', 'Cardiovascular'),
  ('Adalimumab', 'Adalimumab', 'TNF Inhibitor', 'Immunology'),
  ('Alendronate', 'Alendronate', 'Bisphosphonate', 'Supplement'),
  ('Amiloride', 'Amiloride', 'Potassium-sparing Diuretic', 'Cardiovascular'),
  ('Amlodipine', 'Amlodipine', 'Calcium Channel Blocker', 'Cardiovascular'),
  ('Anakinra', 'Anakinra', 'IL-1 Receptor Antagonist', 'Immunology'),
  ('Atenolol', 'Atenolol', 'Beta-blocker', 'Cardiovascular'),
  ('Azathioprine', 'Azathioprine', 'Purine Antimetabolite', 'Immunology'),
  ('Basiliximab', 'Basiliximab', 'IL-2 Receptor Antagonist', 'Immunology'),
  ('Benazepril', 'Benazepril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Betaxolol', 'Betaxolol', 'Beta-blocker', 'Cardiovascular'),
  ('Bisoprolol', 'Bisoprolol', 'Beta-blocker', 'Cardiovascular'),
  ('Bromocriptine', 'Bromocriptine', 'Dopamine Agonist', 'Psychiatric'),
  ('Candesartan', 'Candesartan', 'ARB', 'Cardiovascular'),
  ('Captopril', 'Captopril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Carvedilol', 'Carvedilol', 'Beta-blocker', 'Cardiovascular'),
  ('Celecoxib', 'Celecoxib', 'COX-2 Inhibitor', 'Analgesic'),
  ('Certolizumab', 'Certolizumab', 'TNF Inhibitor', 'Immunology'),
  ('Chlorothiazide', 'Chlorothiazide', 'Thiazide Diuretic', 'Cardiovascular'),
  ('Citalopram', 'Citalopram', 'SSRI', 'Psychiatric'),
  ('Clomipramine', 'Clomipramine', 'Tricyclic Antidepressant', 'Psychiatric'),
  ('Clonidine', 'Clonidine', 'Central Alpha-2 Agonist', 'Cardiovascular'),
  ('Colesevelam', 'Colesevelam', 'Bile Acid Sequestrant', 'Cardiovascular'),
  ('Cyclosporine', 'Cyclosporine', 'Calcineurin Inhibitor', 'Immunology'),
  ('Diclofenac', 'Diclofenac', 'NSAID', 'Analgesic'),
  ('Diltiazem', 'Diltiazem', 'Calcium Channel Blocker', 'Cardiovascular'),
  ('Duloxetine', 'Duloxetine', 'SNRI', 'Psychiatric'),
  ('Enalapril', 'Enalapril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Eplerenone', 'Eplerenone', 'Aldosterone Antagonist', 'Cardiovascular'),
  ('Etanercept', 'Etanercept', 'TNF Inhibitor', 'Immunology'),
  ('Everolimus', 'Everolimus', 'mTOR Inhibitor', 'Immunology'),
  ('Exenatide', 'Exenatide', 'GLP-1 Agonist', 'Antidiabetic'),
  ('Felodipine', 'Felodipine', 'Calcium Channel Blocker', 'Cardiovascular'),
  ('Fluoxetine', 'Fluoxetine', 'SSRI', 'Psychiatric'),
  ('Fosinopril', 'Fosinopril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Furosemide', 'Furosemide', 'Loop Diuretic', 'Cardiovascular'),
  ('Gabapentin', 'Gabapentin', 'Anticonvulsant', 'Psychiatric'),
  ('Glimepiride', 'Glimepiride', 'Sulfonylurea', 'Antidiabetic'),
  ('Golimumab', 'Golimumab', 'TNF Inhibitor', 'Immunology'),
  ('Hydrochlorothiazide', 'Hydrochlorothiazide', 'Thiazide Diuretic', 'Cardiovascular'),
  ('Ibandronate', 'Ibandronate', 'Bisphosphonate', 'Supplement'),
  ('Ibuprofen', 'Ibuprofen', 'NSAID', 'Analgesic'),
  ('Infliximab', 'Infliximab', 'TNF Inhibitor', 'Immunology'),
  ('Isradipine', 'Isradipine', 'Calcium Channel Blocker', 'Cardiovascular'),
  ('Labetalol', 'Labetalol', 'Alpha/Beta-blocker', 'Cardiovascular'),
  ('Lactulose', 'Lactulose', 'Osmotic Laxative', 'GI'),
  ('Leflunomide', 'Leflunomide', 'DMARD', 'Immunology'),
  ('Linagliptin', 'Linagliptin', 'DPP-4 Inhibitor', 'Antidiabetic'),
  ('Liraglutide', 'Liraglutide', 'GLP-1 Agonist', 'Antidiabetic'),
  ('Lisinopril', 'Lisinopril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Losartan', 'Losartan', 'ARB', 'Cardiovascular'),
  ('Methyldopa', 'Methyldopa', 'Central Alpha-2 Agonist', 'Cardiovascular'),
  ('Metolazone', 'Metolazone', 'Thiazide-like Diuretic', 'Cardiovascular'),
  ('Metoprolol', 'Metoprolol', 'Beta-blocker', 'Cardiovascular'),
  ('Miglitol', 'Miglitol', 'Alpha-glucosidase Inhibitor', 'Antidiabetic'),
  ('Minocycline', 'Minocycline', 'Tetracycline', 'Antibiotic'),
  ('Nabumetone', 'Nabumetone', 'NSAID', 'Analgesic'),
  ('Nadolol', 'Nadolol', 'Beta-blocker', 'Cardiovascular'),
  ('Naproxen', 'Naproxen', 'NSAID', 'Analgesic'),
  ('Nateglinide', 'Nateglinide', 'Meglitinide', 'Antidiabetic'),
  ('Nicardipine', 'Nicardipine', 'Calcium Channel Blocker', 'Cardiovascular'),
  ('Nisoldipine', 'Nisoldipine', 'Calcium Channel Blocker', 'Cardiovascular'),
  ('Paroxetine', 'Paroxetine', 'SSRI', 'Psychiatric'),
  ('Perindopril', 'Perindopril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Pioglitazone', 'Pioglitazone', 'Thiazolidinedione', 'Antidiabetic'),
  ('Pramlintide', 'Pramlintide', 'Amylin Analogue', 'Antidiabetic'),
  ('Propranolol', 'Propranolol', 'Beta-blocker', 'Cardiovascular'),
  ('Quinapril', 'Quinapril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Ramipril', 'Ramipril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Risedronate', 'Risedronate', 'Bisphosphonate', 'Supplement'),
  ('Rituximab', 'Rituximab', 'CD20 Monoclonal Antibody', 'Oncology'),
  ('Rosiglitazone', 'Rosiglitazone', 'Thiazolidinedione', 'Antidiabetic'),
  ('Salsalate', 'Salsalate', 'Salicylate', 'Analgesic'),
  ('Saxagliptin', 'Saxagliptin', 'DPP-4 Inhibitor', 'Antidiabetic'),
  ('Sertraline', 'Sertraline', 'SSRI', 'Psychiatric'),
  ('Sitagliptin', 'Sitagliptin', 'DPP-4 Inhibitor', 'Antidiabetic'),
  ('Spironolactone', 'Spironolactone', 'Aldosterone Antagonist', 'Cardiovascular'),
  ('Sulindac', 'Sulindac', 'NSAID', 'Analgesic'),
  ('Tacrolimus', 'Tacrolimus', 'Calcineurin Inhibitor', 'Immunology'),
  ('Tocilizumab', 'Tocilizumab', 'IL-6 Receptor Antagonist', 'Immunology'),
  ('Tolmetin', 'Tolmetin', 'NSAID', 'Analgesic'),
  ('Torsemide', 'Torsemide', 'Loop Diuretic', 'Cardiovascular'),
  ('Trandolapril', 'Trandolapril', 'ACE Inhibitor', 'Cardiovascular'),
  ('Triamterene', 'Triamterene', 'Potassium-sparing Diuretic', 'Cardiovascular'),
  ('Valsartan', 'Valsartan', 'ARB', 'Cardiovascular'),
  ('Venlafaxine', 'Venlafaxine', 'SNRI', 'Psychiatric'),
  ('Verapamil', 'Verapamil', 'Calcium Channel Blocker', 'Cardiovascular')
) AS v(name, generic_name, drug_class, category)
WHERE lower(d.name) = lower(v.name) AND d.drug_class IS DISTINCT FROM v.drug_class;

INSERT INTO public.drug_brands (drug_id, brand, market)
SELECT d.id, v.brand, v.market
FROM (VALUES
  ('Abatacept', 'Orencia', 'US'),
  ('Abciximab', 'ReoPro', 'US'),
  ('Acarbose', 'Precose', 'US'),
  ('Acebutolol', 'Sectral', 'US'),
  ('Adalimumab', 'Humira', 'US'),
  ('Alendronate', 'Fosamax', 'US'),
  ('Amiloride', 'Midamor', 'US'),
  ('Amlodipine', 'Norvasc', 'US'),
  ('Anakinra', 'Kineret', 'US'),
  ('Atenolol', 'Tenormin', 'US'),
  ('Azathioprine', 'Imuran', 'US'),
  ('Basiliximab', 'Simulect', 'US'),
  ('Benazepril', 'Lotensin', 'US'),
  ('Betaxolol', 'Kerlone', 'US'),
  ('Bisoprolol', 'Zebeta', 'US'),
  ('Bromocriptine', 'Cycloset', 'US'),
  ('Bromocriptine', 'Parlodel', 'US'),
  ('Candesartan', 'Atacand', 'US'),
  ('Captopril', 'Capoten', 'US'),
  ('Carvedilol', 'Coreg', 'US'),
  ('Celecoxib', 'Celebrex', 'US'),
  ('Certolizumab', 'Cimzia', 'US'),
  ('Chlorothiazide', 'Diuril', 'US'),
  ('Citalopram', 'Celexa', 'US'),
  ('Clomipramine', 'Anafranil', 'US'),
  ('Clonidine', 'Catapres', 'US'),
  ('Colesevelam', 'Welchol', 'US'),
  ('Cyclosporine', 'Neoral', 'US'),
  ('Cyclosporine', 'Sandimmune', 'US'),
  ('Diclofenac', 'Voltaren', 'US'),
  ('Diltiazem', 'Cardizem', 'US'),
  ('Duloxetine', 'Cymbalta', 'US'),
  ('Enalapril', 'Vasotec', 'US'),
  ('Eplerenone', 'Inspra', 'US'),
  ('Etanercept', 'Enbrel', 'US'),
  ('Everolimus', 'Zortress', 'US'),
  ('Exenatide', 'Byetta', 'US'),
  ('Felodipine', 'Plendil', 'US'),
  ('Fluoxetine', 'Prozac', 'US'),
  ('Fosinopril', 'Monopril', 'US'),
  ('Furosemide', 'Lasix', 'US'),
  ('Gabapentin', 'Neurontin', 'US'),
  ('Glimepiride', 'Amaryl', 'US'),
  ('Golimumab', 'Simponi', 'US'),
  ('Hydrochlorothiazide', 'HydroDIURIL', 'US'),
  ('Hydrochlorothiazide', 'Microzide', 'US'),
  ('Ibandronate', 'Boniva', 'US'),
  ('Ibuprofen', 'Advil', 'US'),
  ('Ibuprofen', 'Motrin', 'US'),
  ('Infliximab', 'Remicade', 'US'),
  ('Isradipine', 'DynaCirc', 'US'),
  ('Labetalol', 'Trandate', 'US'),
  ('Lactulose', 'Enulose', 'US'),
  ('Leflunomide', 'Arava', 'US'),
  ('Linagliptin', 'Tradjenta', 'US'),
  ('Liraglutide', 'Victoza', 'US'),
  ('Lisinopril', 'Zestril', 'US'),
  ('Lisinopril', 'Prinivil', 'US'),
  ('Losartan', 'Cozaar', 'US'),
  ('Methyldopa', 'Aldomet', 'US'),
  ('Metolazone', 'Zaroxolyn', 'US'),
  ('Metoprolol', 'Lopressor', 'US'),
  ('Metoprolol', 'Toprol XL', 'US'),
  ('Miglitol', 'Glyset', 'US'),
  ('Minocycline', 'Dynacin', 'US'),
  ('Minocycline', 'Minocin', 'US'),
  ('Nabumetone', 'Relafen', 'US'),
  ('Nadolol', 'Corgard', 'US'),
  ('Naproxen', 'Aleve', 'US'),
  ('Naproxen', 'Naprosyn', 'US'),
  ('Nateglinide', 'Starlix', 'US'),
  ('Nicardipine', 'Cardene', 'US'),
  ('Nisoldipine', 'Sular', 'US'),
  ('Paroxetine', 'Paxil', 'US'),
  ('Perindopril', 'Aceon', 'US'),
  ('Pioglitazone', 'Actos', 'US'),
  ('Pramlintide', 'Symlin', 'US'),
  ('Propranolol', 'Inderal', 'US'),
  ('Quinapril', 'Accupril', 'US'),
  ('Ramipril', 'Altace', 'US'),
  ('Risedronate', 'Actonel', 'US'),
  ('Rituximab', 'Rituxan', 'US'),
  ('Rosiglitazone', 'Avandia', 'US'),
  ('Salsalate', 'Disalcid', 'US'),
  ('Saxagliptin', 'Onglyza', 'US'),
  ('Sertraline', 'Zoloft', 'US'),
  ('Sitagliptin', 'Januvia', 'US'),
  ('Spironolactone', 'Aldactone', 'US'),
  ('Sulindac', 'Clinoril', 'US'),
  ('Tacrolimus', 'Prograf', 'US'),
  ('Tocilizumab', 'Actemra', 'US'),
  ('Tolmetin', 'Tolectin', 'US'),
  ('Torsemide', 'Demadex', 'US'),
  ('Trandolapril', 'Mavik', 'US'),
  ('Triamterene', 'Dyrenium', 'US'),
  ('Valsartan', 'Diovan', 'US'),
  ('Venlafaxine', 'Effexor', 'US'),
  ('Verapamil', 'Calan', 'US'),
  ('Verapamil', 'Isoptin', 'US')
) AS v(generic, brand, market)
JOIN public.drugs d ON lower(d.name) = lower(v.generic)
ON CONFLICT (drug_id, brand, market) DO NOTHING;
